<?php
declare(strict_types=1);

/* 
 * MIT License
 *
 * Copyright (c) 2018-present, Marks Software GmbH (https://www.marks-software.de/)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

return [
    'MenuHandlers' => [
        'BechlemConnectLight.BechlemModules' => [
            'controller' => [
                'BechlemProducts',
                'BechlemProductAccessories',
                'BechlemBrands',
                'BechlemCategories',
                'BechlemIdentifiers',
                'BechlemPrinters',
                'BechlemPrinterSerieses',
                'BechlemPrinterToSupplies',
                'BechlemResellers',
                'BechlemResellerItems',
                'BechlemSupplies',
                'BechlemSupplySerieses',
                'BechlemSupplyToOemReferences',
                'BechlemSupplyToSupplies',
            ],
            'title' => 'Bechlem Module',
            'icon' => 'barcode',
            'branch' => [
                'BechlemConnectLight.BechlemProductCards' => [
                    'controller' => 'BechlemProducts',
                    'title' => 'Product Cards',
                    'icon' => 'image',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'BechlemProducts',
                        'action' => 'indexCards',
                    ],
                    'options' => ['escape' => false],
                    'position' => 0,
                ],
                'BechlemConnectLight.BechlemProducts' => [
                    'controller' => 'BechlemProducts',
                    'title' => 'Products',
                    'icon' => 'barcode',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'BechlemProducts',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 1,
                ],
                'BechlemConnectLight.BechlemProductAccessories' => [
                    'controller' => 'BechlemProductAccessories',
                    'title' => 'Product Accessories',
                    'icon' => 'barcode',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'BechlemProductAccessories',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 2,
                ],
                'BechlemConnectLight.BechlemBrands' => [
                    'controller' => 'BechlemBrands',
                    'title' => 'Brands',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'BechlemBrands',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 3,
                ],
                'BechlemConnectLight.BechlemCategories' => [
                    'controller' => 'BechlemCategories',
                    'title' => 'Categories',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'BechlemCategories',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 4,
                ],
                'BechlemConnectLight.BechlemIdentifiers' => [
                    'controller' => 'BechlemIdentifiers',
                    'title' => 'Identifiers',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'BechlemIdentifiers',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 5,
                ],
                'BechlemConnectLight.BechlemPrinters' => [
                    'controller' => 'BechlemPrinters',
                    'title' => 'Printers',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'BechlemPrinters',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 6,
                ],
                'BechlemConnectLight.BechlemPrinterSerieses' => [
                    'controller' => 'BechlemPrinterSerieses',
                    'title' => 'Printer Serieses',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'BechlemPrinterSerieses',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 7,
                ],
                'BechlemConnectLight.BechlemPrinterToSupplies' => [
                    'controller' => 'BechlemPrinterToSupplies',
                    'title' => 'Printer To Supplies',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'BechlemPrinterToSupplies',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 8,
                ],
                'BechlemConnectLight.BechlemResellers' => [
                    'controller' => 'BechlemResellers',
                    'title' => 'Resellers',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'BechlemResellers',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 9,
                ],
                'BechlemConnectLight.BechlemResellerItems' => [
                    'controller' => 'BechlemResellerItems',
                    'title' => 'Reseller Items',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'BechlemResellerItems',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 10,
                ],
                'BechlemConnectLight.BechlemSupplies' => [
                    'controller' => 'BechlemSupplies',
                    'title' => 'Supplies',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'BechlemSupplies',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 11,
                ],
                'BechlemConnectLight.BechlemSupplySerieses' => [
                    'controller' => 'BechlemSupplySerieses',
                    'title' => 'Supply Serieses',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'BechlemSupplySerieses',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 12,
                ],
                'BechlemConnectLight.BechlemSupplyToOemReferences' => [
                    'controller' => 'BechlemSupplyToOemReferences',
                    'title' => 'Supply To Oem References',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'BechlemSupplyToOemReferences',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 13,
                ],
                'BechlemConnectLight.BechlemSupplyToSupplies' => [
                    'controller' => 'BechlemSupplyToSupplies',
                    'title' => 'Supply To Supplies',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'BechlemSupplyToSupplies',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 14,
                ],
            ],
            'options' => ['escape' => false],
            'position' => 10,
        ],
        'BechlemConnectLight.ProductsModules' => [
            'controller' => [
                'Products',
                'ProductTypes',
                'ProductTypeAttributes',
                'ProductTypeAttributeChoices',
                'ProductProductTypeAttributeValues',
                'ProductManufacturers',
                'ProductBrands',
                'ProductCategories',
                'ProductConditions',
                'ProductDeliveryTimes',
                'ProductTaxClasses',
                'ProductIntrastatCodes',
                'ProductSuppliers',
            ],
            'title' => 'Product Module',
            'icon' => 'barcode',
            'branch' => [
                'BechlemConnectLight.Products' => [
                    'controller' => 'Products',
                    'title' => 'Products',
                    'icon' => 'file',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'Products',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 10,
                ],
                'BechlemConnectLight.ProductTypes' => [
                    'controller' => 'ProductTypes',
                    'title' => 'Types',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'ProductTypes',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 20,
                ],
                'BechlemConnectLight.ProductTypeAttributes' => [
                    'controller' => 'ProductTypeAttributes',
                    'title' => 'Type Attributes',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'ProductTypeAttributes',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 30,
                ],
                'BechlemConnectLight.ProductTypeAttributeChoices' => [
                    'controller' => 'ProductTypeAttributeChoices',
                    'title' => 'Type Attribute Choices',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'ProductTypeAttributeChoices',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 40,
                ],
                'BechlemConnectLight.ProductProductTypeAttributeValues' => [
                    'controller' => 'ProductProductTypeAttributeValues',
                    'title' => 'Type Attribute Values',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'ProductProductTypeAttributeValues',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 50,
                ],
                'BechlemConnectLight.ProductManufacturers' => [
                    'controller' => 'ProductManufacturers',
                    'title' => 'Manufacturers',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'ProductManufacturers',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 60,
                ],
                'BechlemConnectLight.ProductBrands' => [
                    'controller' => 'ProductBrands',
                    'title' => 'Brands',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'ProductBrands',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 70,
                ],
                'BechlemConnectLight.ProductCategories' => [
                    'controller' => 'ProductCategories',
                    'title' => 'Categories',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'ProductCategories',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 80,
                ],
                'BechlemConnectLight.ProductConditions' => [
                    'controller' => 'ProductConditions',
                    'title' => 'Conditions',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'ProductConditions',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 90,
                ],
                'BechlemConnectLight.ProductDeliveryTimes' => [
                    'controller' => 'ProductDeliveryTimes',
                    'title' => 'Delivery Times',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'ProductDeliveryTimes',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 100,
                ],
                'BechlemConnectLight.ProductTaxClasses' => [
                    'controller' => 'ProductTaxClasses',
                    'title' => 'Tax Classes',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'ProductTaxClasses',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 110,
                ],
                'BechlemConnectLight.ProductIntrastatCodes' => [
                    'controller' => 'ProductIntrastatCodes',
                    'title' => 'Intrastat Codes',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'ProductIntrastatCodes',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 120,
                ],
                'BechlemConnectLight.ProductSuppliers' => [
                    'controller' => 'ProductSuppliers',
                    'title' => 'Suppliers',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'ProductSuppliers',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 130,
                ],
            ],
            'options' => ['escape' => false],
            'position' => 20,
        ],
        'BechlemConnectLight.BechlemConnect' => [
            'controller' => [
                'BechlemConnectConfigs',
                'BechlemConnectRequests',
            ],
            'title' => 'Bechlem Connect',
            'icon' => 'cloud',
            'branch' => [
                'BechlemConnectLight.BechlemConnectConfigs' => [
                    'controller' => 'BechlemConnectConfigs',
                    'title' => 'Configs',
                    'icon' => 'cog',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'BechlemConnectConfigs',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 1,
                ],
                'BechlemConnectLight.BechlemConnectRequests' => [
                    'controller' => 'BechlemConnectRequests',
                    'title' => 'Requests',
                    'icon' => 'arrows-alt-h',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'BechlemConnectRequests',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 2,
                ],
            ],
            'options' => ['escape' => false],
            'position' => 30,
        ],
        'BechlemConnectLight.RolesUsersModules' => [
            'controller' => [
                'Users',
                'UserProfiles',
                'Roles',
                'Registrations',
                'RegistrationTypes',
            ],
            'title' => 'Roles & Users',
            'icon' => 'user',
            'branch' => [
                'BechlemConnectLight.Roles' => [
                    'controller' => 'Roles',
                    'title' => 'Roles',
                    'icon' => 'user',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'Roles',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 1,
                ],
                'BechlemConnectLight.Users' => [
                    'controller' => 'Users',
                    'title' => 'Users',
                    'icon' => 'user',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'Users',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 2,
                ],
                'BechlemConnectLight.UserProfiles' => [
                    'controller' => 'UserProfiles',
                    'title' => 'User Profiles',
                    'icon' => 'users',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'UserProfiles',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 3,
                ],
                'BechlemConnectLight.Registrations' => [
                    'controller' => 'Registrations',
                    'title' => 'Registrations',
                    'icon' => 'user',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'Registrations',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 4,
                ],
                'BechlemConnectLight.RegistrationTypes' => [
                    'controller' => 'RegistrationTypes',
                    'title' => 'Registration Types',
                    'icon' => 'list',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'RegistrationTypes',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 5,
                ],
            ],
            'options' => ['escape' => false],
            'position' => 40,
        ],
        'BechlemConnectLight.Domains' => [
            'controller' => 'Domains',
            'title' => 'Domains',
            'icon' => 'globe',
            'link' => [
                'prefix' => 'Admin',
                'plugin' => 'BechlemConnectLight',
                'controller' => 'Domains',
                'action' => 'index',
            ],
            'options' => ['escape' => false],
            'position' => 50,
        ],
        'BechlemConnectLight.LocalesCountries' => [
            'controller' => [
                'Locales',
                'Countries',
            ],
            'title' => 'Locales',
            'icon' => 'globe',
            'branch' => [
                'BechlemConnectLight.Locales' => [
                    'controller' => 'Locales',
                    'title' => 'Locales',
                    'icon' => 'globe',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'Locales',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 1,
                ],
                'BechlemConnectLight.Countries' => [
                    'controller' => 'Countries',
                    'title' => 'Countries',
                    'icon' => 'globe',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'Countries',
                        'action' => 'index',
                    ],
                    'options' => ['escape' => false],
                    'position' => 2,
                ],
            ],
            'options' => ['escape' => false],
            'position' => 60,
        ],
        'BechlemConnectLight.Logs' => [
            'controller' => 'Logs',
            'title' => 'Logs',
            'icon' => 'file',
            'link' => [
                'prefix' => 'Admin',
                'plugin' => 'BechlemConnectLight',
                'controller' => 'Logs',
                'action' => 'index',
            ],
            'options' => ['escape' => false],
            'position' => 70,
        ],
        'BechlemConnectLight.CachesLogsSessions' => [
            'controller' => [
                'AppCaches',
                'AppLogs',
                'AppSessions',
            ],
            'title' => 'App Data',
            'icon' => 'trash',
            'branch' => [
                'BechlemConnectLight.AppCaches' => [
                    'controller' => 'AppCaches',
                    'title' => 'Clear Caches',
                    'icon' => 'trash',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'AppCaches',
                        'action' => 'clearAppCaches',
                    ],
                    'options' => ['escape' => false],
                    'position' => 1,
                ],
                'BechlemConnectLight.AppLogs' => [
                    'controller' => 'AppLogs',
                    'title' => 'Clear Logs',
                    'icon' => 'trash',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'AppLogs',
                        'action' => 'clearAppLogs',
                    ],
                    'options' => ['escape' => false],
                    'position' => 2,
                ],
                'BechlemConnectLight.AppSessions' => [
                    'controller' => 'AppSessions',
                    'title' => 'Clear Sessions',
                    'icon' => 'trash',
                    'link' => [
                        'prefix' => 'Admin',
                        'plugin' => 'BechlemConnectLight',
                        'controller' => 'AppSessions',
                        'action' => 'clearAppSessions',
                    ],
                    'options' => ['escape' => false],
                    'position' => 3,
                ],
            ],
            'options' => ['escape' => false],
            'position' => 80,
        ],
        'BechlemConnectLight.Settings' => [
            'controller' => 'Settings',
            'title' => 'Settings',
            'icon' => 'cog',
            'link' => [
                'prefix' => 'Admin',
                'plugin' => 'BechlemConnectLight',
                'controller' => 'Settings',
                'action' => 'index',
            ],
            'options' => ['escape' => false],
            'position' => 90,
        ],
    ],
];
