<?php
declare(strict_types=1);

/* 
 * MIT License
 *
 * Copyright (c) 2018-present, Marks Software GmbH (https://www.marks-software.de/)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
use Cake\I18n\DateTime;
use Migrations\AbstractSeed;

/**
 * BechlemPrinterSerieses seed.
 */
class BechlemPrinterSeriesesSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     *
     * @return void
     */
    public function run(): void
    {
        $dateTime = DateTime::now();

        $data = [
            [
                'id' => 1,
                'uuid_id' => '16c0f889-8946-4b55-aa29-8253f110288e',
                'id_printer_series' => '34000666',
                'id_brand' => '20000984',
                'brand' => 'Kyocera',
                'name' => 'FS',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 2,
                'uuid_id' => '1c9b2d75-22a3-42d4-b28c-ee7573b2aa49',
                'id_printer_series' => '34000674',
                'id_brand' => '20000984',
                'brand' => 'Kyocera',
                'name' => 'KM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 3,
                'uuid_id' => 'a7e4954c-9625-42de-bd60-3425bc2b5cb1',
                'id_printer_series' => '34001269',
                'id_brand' => '20000984',
                'brand' => 'Kyocera',
                'name' => 'LP',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 4,
                'uuid_id' => 'bcc82cb3-828e-46fa-90a7-9478977a9526',
                'id_printer_series' => '31000063',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'BJ',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 5,
                'uuid_id' => 'cd7e0fe8-68d1-44f7-bf93-ab43d9415b4f',
                'id_printer_series' => '31000064',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'BJC',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 6,
                'uuid_id' => '5c90ab71-b6c3-45eb-a4fc-ae3d71ef1df8',
                'id_printer_series' => '31000074',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'CFX',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 7,
                'uuid_id' => 'f0745d7b-e8f8-4a4b-93e4-7682825d2b8a',
                'id_printer_series' => '31000086',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'Fax L',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 8,
                'uuid_id' => '3e554666-1812-4463-950f-ef395ff5b832',
                'id_printer_series' => '31000088',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'Faxphone',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 9,
                'uuid_id' => 'cf4620ba-7c94-4a43-a054-8efdfef37f2c',
                'id_printer_series' => '31000092',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'I',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 10,
                'uuid_id' => '831c9a4c-4dab-4b63-babc-87a19bed65db',
                'id_printer_series' => '31000094',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'imageCLASS D',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 11,
                'uuid_id' => '52162e29-743e-47ae-b6ff-a20d129cac27',
                'id_printer_series' => '31000095',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'imageCLASS MF',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 12,
                'uuid_id' => 'e6005666-9a40-4cb9-80f2-7884eca42a0f',
                'id_printer_series' => '31000096',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'imageCLASS',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 13,
                'uuid_id' => '07a57188-4372-4387-9180-a7770e934b66',
                'id_printer_series' => '31000099',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'imageRUNNER C',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 14,
                'uuid_id' => '74adef22-ace9-4b24-938d-6b2ec3bac8f7',
                'id_printer_series' => '31000100',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'imageRUNNER',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 15,
                'uuid_id' => 'f871e816-9e29-4222-85e9-41db3af2a2a1',
                'id_printer_series' => '31000102',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'IR-C',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 16,
                'uuid_id' => 'fef80b08-77db-49c9-a1a6-e9d834a7c251',
                'id_printer_series' => '31000103',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'IR',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 17,
                'uuid_id' => '19a9466a-edd7-4fa4-b5e8-6bf0e109142f',
                'id_printer_series' => '31000106',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'Laser Class',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 18,
                'uuid_id' => 'd0d6026e-0199-4f94-a992-77458c38f222',
                'id_printer_series' => '31000107',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'Laserbase',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 19,
                'uuid_id' => '6673f3b0-01d9-4dfd-acf6-02fc5dfa030e',
                'id_printer_series' => '31000108',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'Lasershot',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 20,
                'uuid_id' => '0434b8fd-8857-4f57-b8a7-7722d7d0dd72',
                'id_printer_series' => '31000109',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'LBP',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 21,
                'uuid_id' => '8e58d24b-dd56-4a00-943e-cd2582f6eb36',
                'id_printer_series' => '31000112',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'Multipass',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 22,
                'uuid_id' => 'b75bb2cd-a0b9-4569-9b53-01f58adbf6c2',
                'id_printer_series' => '31000119',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'PC-D',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 23,
                'uuid_id' => 'f7479681-9061-4325-a7c0-5ad817f203ee',
                'id_printer_series' => '31000120',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'Pixma',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 24,
                'uuid_id' => '052e6fbb-70ce-4844-b486-5bc85bbe930c',
                'id_printer_series' => '31001213',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'i-SENSYS',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 25,
                'uuid_id' => '697e4ae3-f9f3-45eb-babf-eaf72e8cadad',
                'id_printer_series' => '31001230',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'Fax JX',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 26,
                'uuid_id' => '94233c83-9585-4b71-8b3c-bbfc339dcdf7',
                'id_printer_series' => '31000127',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'S',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 27,
                'uuid_id' => '7bb4f758-fdf7-45b0-94f3-dbb88d68cc3c',
                'id_printer_series' => '34001707',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'Fax',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 28,
                'uuid_id' => '60a4f7d6-24e1-4c5e-bd6d-9d94f008e82b',
                'id_printer_series' => '34001708',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'BJ',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 29,
                'uuid_id' => 'c72e598f-8800-45f8-98ae-0e2550af9fe6',
                'id_printer_series' => '34001710',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'imageCLASS',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 30,
                'uuid_id' => '09488a9c-ab9f-424e-b0f8-4e5dea053b33',
                'id_printer_series' => '34001711',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'imageRUNNER',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 31,
                'uuid_id' => '800f173c-6614-4816-8213-f07aeaa2b7c5',
                'id_printer_series' => '34001712',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'IR',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 32,
                'uuid_id' => '42ac8aa7-0359-4e67-ae82-094b3ffe58d8',
                'id_printer_series' => '34001713',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'PC',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 33,
                'uuid_id' => 'c50b35ab-7b54-4568-afad-a28e02a505f4',
                'id_printer_series' => '34002112',
                'id_brand' => '20000264',
                'brand' => 'Canon',
                'name' => 'imagePROGRAF',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 34,
                'uuid_id' => '38fafee0-4088-4217-8a91-08341afeb528',
                'id_printer_series' => '34000664',
                'id_brand' => '20001289',
                'brand' => 'Sharp',
                'name' => 'UX',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 35,
                'uuid_id' => 'bcabf8c7-b521-4ad2-975c-b924cea3322f',
                'id_printer_series' => '34000669',
                'id_brand' => '20001289',
                'brand' => 'Sharp',
                'name' => 'XE',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 36,
                'uuid_id' => 'd23fcb38-c2bf-4a9e-bf9a-d84ec5ef5088',
                'id_printer_series' => '34000675',
                'id_brand' => '20001289',
                'brand' => 'Sharp',
                'name' => 'AR',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 37,
                'uuid_id' => '413167bb-9d5b-4feb-a002-94222baef85c',
                'id_printer_series' => '34000676',
                'id_brand' => '20001289',
                'brand' => 'Sharp',
                'name' => 'FO',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 38,
                'uuid_id' => '57302a52-eb34-40fa-9b8f-fcfe176f06c0',
                'id_printer_series' => '34000677',
                'id_brand' => '20001289',
                'brand' => 'Sharp',
                'name' => 'NX',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 39,
                'uuid_id' => '41d21873-577e-4b23-8873-025ac41f1216',
                'id_printer_series' => '34000678',
                'id_brand' => '20001289',
                'brand' => 'Sharp',
                'name' => 'PA',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 40,
                'uuid_id' => 'ed3c3bd2-d6bd-4042-a5a2-a36e005e3b6f',
                'id_printer_series' => '34000693',
                'id_brand' => '20001289',
                'brand' => 'Sharp',
                'name' => 'AL',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 41,
                'uuid_id' => 'd69d7147-95af-4c3f-ae0c-82e78812c7c6',
                'id_printer_series' => '34000694',
                'id_brand' => '20001289',
                'brand' => 'Sharp',
                'name' => 'ER',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 42,
                'uuid_id' => 'cea53d12-d8cd-43a3-9d62-515ff2fd2b2f',
                'id_printer_series' => '34000679',
                'id_brand' => '20001289',
                'brand' => 'Sharp',
                'name' => 'PA',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 43,
                'uuid_id' => '10d7c5ba-7272-4be8-987a-c066dbdf1548',
                'id_printer_series' => '34000680',
                'id_brand' => '20001289',
                'brand' => 'Sharp',
                'name' => 'PA',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 44,
                'uuid_id' => '9a96dc5e-851d-458f-858d-f39cd1fe0f65',
                'id_printer_series' => '34001918',
                'id_brand' => '20001289',
                'brand' => 'Sharp',
                'name' => 'MX',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 45,
                'uuid_id' => '972984fa-1db3-490b-a670-4fddb7cebf1d',
                'id_printer_series' => '34001277',
                'id_brand' => '20000784',
                'brand' => 'Infotec',
                'name' => 'MP',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 46,
                'uuid_id' => '11423a2c-0bde-4e0b-873f-d62cca5d3c61',
                'id_printer_series' => '34000670',
                'id_brand' => '20001295',
                'brand' => 'Wincor-Nixdorf',
                'name' => 'Highprint',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 47,
                'uuid_id' => 'd05090e1-9ebf-4ec1-9311-237c2501b1e7',
                'id_printer_series' => '34000696',
                'id_brand' => '20000827',
                'brand' => 'Jetfax',
                'name' => 'Jetfax',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 48,
                'uuid_id' => '790df69c-e286-42d8-8e8b-ff4f0e99b28b',
                'id_printer_series' => '34000651',
                'id_brand' => '20001076',
                'brand' => 'Olivetti',
                'name' => 'DP',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 49,
                'uuid_id' => '17e8a065-2074-4481-8d36-42d657b55f07',
                'id_printer_series' => '34000691',
                'id_brand' => '20001077',
                'brand' => 'Olympia',
                'name' => 'Omega',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 50,
                'uuid_id' => '58032e85-74a3-4304-848e-48397dffe951',
                'id_printer_series' => '34000687',
                'id_brand' => '20001099',
                'brand' => 'Panasonic',
                'name' => 'FP',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 51,
                'uuid_id' => '1a77d21e-52ef-40cf-919a-4a2070a45fa1',
                'id_printer_series' => '34000688',
                'id_brand' => '20001099',
                'brand' => 'Panasonic',
                'name' => 'FP',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 52,
                'uuid_id' => 'bb4dbb49-7540-4230-a0e6-f7dcbf05a6ca',
                'id_printer_series' => '34001702',
                'id_brand' => '20000391',
                'brand' => 'CPF',
                'name' => 'Fax',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 53,
                'uuid_id' => '78dfa5c2-17d4-4806-9fc5-78f201d64a72',
                'id_printer_series' => '34001701',
                'id_brand' => '20000681',
                'brand' => 'Gestetner',
                'name' => 'Docustation',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 54,
                'uuid_id' => '81c84929-5305-46bc-a979-92a0d397d56e',
                'id_printer_series' => '34001356',
                'id_brand' => '20000681',
                'brand' => 'Gestetner',
                'name' => 'MP',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 55,
                'uuid_id' => '4ef39eda-159a-4652-b488-65ddb147ee61',
                'id_printer_series' => '34000653',
                'id_brand' => '20000746',
                'brand' => 'IBM',
                'name' => 'Infoprint',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 56,
                'uuid_id' => '404a031e-bafb-4af2-9f0d-a38d09cfdeeb',
                'id_printer_series' => '34000673',
                'id_brand' => '20001237',
                'brand' => 'Sagem',
                'name' => 'MF',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 57,
                'uuid_id' => '34abdb12-8b1c-4d74-ac76-57fcc8752479',
                'id_printer_series' => '34001273',
                'id_brand' => '20001237',
                'brand' => 'Sagem',
                'name' => 'Fax',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 58,
                'uuid_id' => '88e00724-d24e-4ccf-8499-bfa49f2fbfbd',
                'id_printer_series' => '34000695',
                'id_brand' => '20001250',
                'brand' => 'Sanyo',
                'name' => 'SFT',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 59,
                'uuid_id' => 'e01ed929-a143-4229-be06-43d5d6e5f5ed',
                'id_printer_series' => '34001129',
                'id_brand' => '20001535',
                'brand' => 'Xerox',
                'name' => 'Docuprint',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 60,
                'uuid_id' => 'b91b0496-c555-4c7a-8e16-c4fc978d1803',
                'id_printer_series' => '34001130',
                'id_brand' => '20001535',
                'brand' => 'Xerox',
                'name' => 'WorkCentre',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 61,
                'uuid_id' => '0d2ccbc6-b402-44be-8090-d5d9dca5398c',
                'id_printer_series' => '34001131',
                'id_brand' => '20001535',
                'brand' => 'Xerox',
                'name' => 'X',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 62,
                'uuid_id' => '33229ca5-8517-471c-ad15-8a3b7f474ebe',
                'id_printer_series' => '34000657',
                'id_brand' => '20000728',
                'brand' => 'HP',
                'name' => 'OfficeJet',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 63,
                'uuid_id' => '8fd6ba6e-655d-47bc-86ae-91f50d3ba8b6',
                'id_printer_series' => '34000662',
                'id_brand' => '20000728',
                'brand' => 'HP',
                'name' => 'DesignJet',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 64,
                'uuid_id' => 'fa5f50f6-5b8b-48d9-83bf-30f152097c44',
                'id_printer_series' => '34000667',
                'id_brand' => '20000728',
                'brand' => 'HP',
                'name' => 'LaserJet',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 65,
                'uuid_id' => '1b1f906a-fcc5-4b04-9959-93462fcd0313',
                'id_printer_series' => '34000671',
                'id_brand' => '20000728',
                'brand' => 'HP',
                'name' => 'PhotoSmart',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 66,
                'uuid_id' => 'b8abc110-d9c5-44ec-b416-179ef2c78950',
                'id_printer_series' => '34002035',
                'id_brand' => '20000728',
                'brand' => 'HP',
                'name' => 'DeskJet',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 67,
                'uuid_id' => '29a50d99-fe94-4cd8-b22a-9105570f3652',
                'id_printer_series' => '34000423',
                'id_brand' => '20000569',
                'brand' => 'EGT',
                'name' => 'Agoris',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 68,
                'uuid_id' => 'ff8772c1-00f2-451a-8c5d-bb33fe7a6b0c',
                'id_printer_series' => '34000645',
                'id_brand' => '20000593',
                'brand' => 'Epson',
                'name' => 'Stylus',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 69,
                'uuid_id' => 'c1fe99ae-462e-4cbf-ab9a-3bea54b6d1e7',
                'id_printer_series' => '34000649',
                'id_brand' => '20000593',
                'brand' => 'Epson',
                'name' => 'TM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 70,
                'uuid_id' => '5e0396e1-f19a-4f29-ad46-00edaf7a0893',
                'id_printer_series' => '34000738',
                'id_brand' => '20000593',
                'brand' => 'Epson',
                'name' => 'Workforce',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 71,
                'uuid_id' => '572af3d6-5ad5-4d45-ae42-91f1b30c46a0',
                'id_printer_series' => '34000692',
                'id_brand' => '20000593',
                'brand' => 'Epson',
                'name' => 'Expression',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 72,
                'uuid_id' => 'f767261b-3a4b-4f03-b92c-b28297133400',
                'id_printer_series' => '34001716',
                'id_brand' => '20000593',
                'brand' => 'Epson',
                'name' => 'EPL',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 73,
                'uuid_id' => '19d620c9-7563-44e1-8026-0827c057e586',
                'id_printer_series' => '34001717',
                'id_brand' => '20000593',
                'brand' => 'Epson',
                'name' => 'M',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 74,
                'uuid_id' => '51b90357-8fd1-4b12-9d6f-49345e002d98',
                'id_printer_series' => '34000647',
                'id_brand' => '20000593',
                'brand' => 'Epson',
                'name' => 'Stylus',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 75,
                'uuid_id' => '3795da9f-56a5-4c7d-95a9-ec59c4bf09bf',
                'id_printer_series' => '34001271',
                'id_brand' => '20001122',
                'brand' => 'Philips',
                'name' => 'Fax',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 76,
                'uuid_id' => '5ffa0859-82f4-4592-b64e-c40b41c9c7f3',
                'id_printer_series' => '34002034',
                'id_brand' => '20001145',
                'brand' => 'Xante',
                'name' => 'Colourlaser',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 77,
                'uuid_id' => '2dd83493-ecc5-4fef-8493-285072c0502b',
                'id_printer_series' => '34001714',
                'id_brand' => '20002389',
                'brand' => 'NRG',
                'name' => 'MP',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 78,
                'uuid_id' => '3c7c709f-5471-4c3b-b990-9fadb8435e28',
                'id_printer_series' => '34001715',
                'id_brand' => '20002389',
                'brand' => 'NRG',
                'name' => 'SP',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 79,
                'uuid_id' => '5ba7db2d-7597-46d8-bcc8-3f6a6863a8e7',
                'id_printer_series' => '34001719',
                'id_brand' => '20002389',
                'brand' => 'NRG',
                'name' => 'Docustation',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 80,
                'uuid_id' => '7d6277cd-558b-4a7c-a6a6-e7cfd8135d90',
                'id_printer_series' => '34000658',
                'id_brand' => '20001164',
                'brand' => 'Konica Minolta',
                'name' => 'Pagepro',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 81,
                'uuid_id' => '56b8a7c1-8078-431d-9d24-7bae6b2638e8',
                'id_printer_series' => '34000665',
                'id_brand' => '20001164',
                'brand' => 'Konica Minolta',
                'name' => 'Bizhub',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 82,
                'uuid_id' => '22b30fa0-5f23-4dae-903f-4d519efb0558',
                'id_printer_series' => '34001268',
                'id_brand' => '20001164',
                'brand' => 'Konica Minolta',
                'name' => 'Fax',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 83,
                'uuid_id' => 'b50ef49c-3e82-44b2-a998-0ab47c40bf34',
                'id_printer_series' => '31001020',
                'id_brand' => '20001400',
                'brand' => 'Telekom',
                'name' => 'T-Fax',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 84,
                'uuid_id' => '9b225f3c-270a-4094-b6f2-70a6660b6f70',
                'id_printer_series' => '34000661',
                'id_brand' => '20000886',
                'brand' => 'Lexmark',
                'name' => 'Optra',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 85,
                'uuid_id' => 'da548e3f-8237-44ea-b987-981e0e8c580f',
                'id_printer_series' => '34001703',
                'id_brand' => '20000229',
                'brand' => 'Brother',
                'name' => 'Fax',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 86,
                'uuid_id' => '6446c86b-b3f0-4008-b279-f8f53b080d28',
                'id_printer_series' => '34001704',
                'id_brand' => '20000229',
                'brand' => 'Brother',
                'name' => 'HL',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 87,
                'uuid_id' => '657101d2-bc15-4d5d-91b2-1f45b7f44b8f',
                'id_printer_series' => '34001705',
                'id_brand' => '20000229',
                'brand' => 'Brother',
                'name' => 'MFC',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 88,
                'uuid_id' => '2aa5fa83-b28c-4f28-b555-75fd3de86797',
                'id_printer_series' => '34001706',
                'id_brand' => '20000229',
                'brand' => 'Brother',
                'name' => 'P',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 89,
                'uuid_id' => '44fa23f0-841e-43e5-abda-45c01ca9259b',
                'id_printer_series' => '34002198',
                'id_brand' => '20000229',
                'brand' => 'Brother',
                'name' => 'DCP',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 90,
                'uuid_id' => '20175afe-24ac-466e-9df2-e367c57ba9d8',
                'id_printer_series' => '34001272',
                'id_brand' => '20001210',
                'brand' => 'Rex Rotary',
                'name' => 'Docustation',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 91,
                'uuid_id' => 'e58c9dde-9a0a-4ee7-9e82-d0285e5230ef',
                'id_printer_series' => '34000672',
                'id_brand' => '20001214',
                'brand' => 'Ricoh',
                'name' => 'LP',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 92,
                'uuid_id' => '49780b31-5491-46c1-9b07-7dffbbf69433',
                'id_printer_series' => '34001128',
                'id_brand' => '20001214',
                'brand' => 'Ricoh',
                'name' => 'Aficio',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 93,
                'uuid_id' => '9541a3c6-3261-4db1-b5da-486f4510e58b',
                'id_printer_series' => '34001369',
                'id_brand' => '20001214',
                'brand' => 'Ricoh',
                'name' => 'MP',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 94,
                'uuid_id' => '281980e3-2f89-42bd-98cb-69c7515f951c',
                'id_printer_series' => '34000654',
                'id_brand' => '20001434',
                'brand' => 'Toshiba',
                'name' => 'TF',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 95,
                'uuid_id' => '260dadb4-7480-45c4-be64-5972f5b8c985',
                'id_printer_series' => '34000655',
                'id_brand' => '20001434',
                'brand' => 'Toshiba',
                'name' => 'TF',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
        ];

        $table = $this->table('bechlem_printer_serieses');
        $table->insert($data)->save();
    }
}
