<?php
declare(strict_types=1);

/* 
 * MIT License
 *
 * Copyright (c) 2018-present, Marks Software GmbH (https://www.marks-software.de/)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
use Cake\I18n\DateTime;
use Cake\Utility\Text;
use Migrations\AbstractSeed;

/**
 * BechlemResellerItems seed.
 */
class BechlemResellerItemsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     *
     * @return void
     */
    public function run(): void
    {
        $dateTime = DateTime::now();

        $data = [
            [
                'id' => 1,
                'uuid_id' => '92632d8a-9dc2-4015-a10c-9c893b749819',
                'id_art_nr' => '361707',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50043547',
                'ean' => '4012700361707',
                'oem_nr' => '361707',
                'description' => 'Pelikan 361707/C28 Ink cartridge cyan, 1.365 pages 13ml (replaces Canon CLI-8C)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 2,
                'uuid_id' => '97eaf904-29b1-4ff8-bac1-12efb53c51f4',
                'id_art_nr' => '361721',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50043549',
                'ean' => '4012700361721',
                'oem_nr' => '361721',
                'description' => 'Pelikan 361721/C30 Ink cartridge yellow, 950 pages 13ml (replaces Canon CLI-8Y)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 3,
                'uuid_id' => '95051783-cbb1-4b7f-abc4-928a6d69af15',
                'id_art_nr' => '361738',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50043550',
                'ean' => '4018474361738',
                'oem_nr' => '361738',
                'description' => 'Pelikan 361738/C32 Ink cartridge light cyan 13ml (replaces Canon CLI-8PC)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 4,
                'uuid_id' => '355051de-4e37-45f1-9cd2-2107bc51eca0',
                'id_art_nr' => '361745',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50043551',
                'ean' => '4018474361745',
                'oem_nr' => '361745',
                'description' => 'Pelikan 361745/C33 Ink cartridge light magenta 13ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 5,
                'uuid_id' => '1f8e4f6c-e7f7-4061-8fc1-2ed5451d0822',
                'id_art_nr' => '1505,0006',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50045805',
                'ean' => '4011324505061',
                'oem_nr' => '1505,0006',
                'description' => 'KMP 1505,0006/C68 Ink cartridge magenta, 420 pages ISO/IEC 24711 13ml (replaces Canon CLI-8M)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 6,
                'uuid_id' => 'd90e6a2b-ef6d-4c49-91f2-c4c0a5b15087',
                'id_art_nr' => '1505,0046',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50046062',
                'ean' => '4011324150568',
                'oem_nr' => '1505,0046',
                'description' => 'KMP 1505,0046/C71 Ink cartridge light magenta 13ml (replaces Canon CLI-8PM)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 7,
                'uuid_id' => '56953ce2-e130-442a-8581-03d2a2d15339',
                'id_art_nr' => '629517',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50042829',
                'ean' => '4018474629517',
                'oem_nr' => '629517',
                'description' => 'Pelikan 629517/1176 Toner cartridge, 1x2.100 pages/5% 120 grams Pack=1 (replaces Canon FX-10)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 8,
                'uuid_id' => '3a66896e-d175-40e0-b420-14c3f32434a5',
                'id_art_nr' => '627650',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50042922',
                'ean' => '4018474627650',
                'oem_nr' => '627650',
                'description' => 'Pelikan 627650/1121 Toner cartridge black, 1x3.900 pages/5% 170 grams Pack=1 (replaces Canon EP-27)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 9,
                'uuid_id' => '88bde2d4-7c23-4f32-84c5-332185f04c5c',
                'id_art_nr' => '619239',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50009064',
                'ean' => '4018474619235',
                'oem_nr' => '619239',
                'description' => 'Pelikan 619239/858 Toner cartridge black recycled, 1x2.700 pages/5% 155 grams Pack=1 (replaces Canon FX-3)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 10,
                'uuid_id' => '2a9c43c9-26ed-46a5-8edd-833efa6d0222',
                'id_art_nr' => '361752',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50043546',
                'ean' => '4018474101273',
                'oem_nr' => '361752',
                'description' => 'Pelikan 361752/C27 Ink cartridge black, 5.075 pages 13ml (replaces Canon CLI-8BK)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 11,
                'uuid_id' => 'f4b74db0-50f2-4072-8c4d-90d423e9dfa0',
                'id_art_nr' => '4103208',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50074176',
                'ean' => '4018474103208',
                'oem_nr' => '4103208',
                'description' => 'Pelikan 4103208/C35 Ink cartridge color, 3x202 pages 6ml Pack=3 (replaces Canon CL-41)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 12,
                'uuid_id' => '39afa735-e814-42d0-a409-e95b9694bfde',
                'id_art_nr' => '4103192',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50074202',
                'ean' => '4018474103192',
                'oem_nr' => '4103192',
                'description' => 'Pelikan 4103192/C34 Ink cartridge black, 250 pages 20ml (replaces Canon PG-40)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 13,
                'uuid_id' => '982f6350-8883-4260-a395-db888ee6fbca',
                'id_art_nr' => '4103239',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50074203',
                'ean' => '4018474103239',
                'oem_nr' => '4103239',
                'description' => 'Pelikan 4103239/C36 Ink cartridge black pigmented, 405 pages ISO/IEC 19752 19ml (replaces Canon PGI-520PGBK)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 14,
                'uuid_id' => '60969e90-7c0e-4630-b1b6-2f61af7ed2f1',
                'id_art_nr' => '4103246',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50074204',
                'ean' => '4018474103246',
                'oem_nr' => '4103246',
                'description' => 'Pelikan 4103246/C37 Ink cartridge foto black, 3.425 pages ISO/IEC 24711 9ml (replaces Canon CLI-521BK)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 15,
                'uuid_id' => 'fb725629-a32b-479a-9b8c-e1232f1eca15',
                'id_art_nr' => '4103253',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50074205',
                'ean' => '4018474103253',
                'oem_nr' => '4103253',
                'description' => 'Pelikan 4103253/C38 Ink cartridge cyan, 755 pages ISO/IEC 19752 9ml (replaces Canon CLI-521C)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 16,
                'uuid_id' => 'a4b7a8b4-5d8a-4f63-89f4-8662abde75e0',
                'id_art_nr' => '4103260',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50074206',
                'ean' => '4018474103260',
                'oem_nr' => '4103260',
                'description' => 'Pelikan 4103260/C39 Ink cartridge magenta, 708 pages 9ml (replaces Canon CLI-521M)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 17,
                'uuid_id' => '5eccedca-d544-42ef-98ee-a71421b61875',
                'id_art_nr' => '4103277',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50074207',
                'ean' => '4018474103277',
                'oem_nr' => '4103277',
                'description' => 'Pelikan 4103277/C40 Ink cartridge yellow, 662 pages ISO/IEC 19752 9ml (replaces Canon CLI-521Y)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 18,
                'uuid_id' => '7c1ca793-2aa8-4e4a-8fa1-6779357f3751',
                'id_art_nr' => '4103291',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50074214',
                'ean' => '4018474103291',
                'oem_nr' => '4103291',
                'description' => 'Pelikan 4103291/P19 Ink cartridge multi pack C,M,Y, 3x755 pages ISO/IEC 19752 9ml Pack=3 (replaces Canon CLI-521)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 19,
                'uuid_id' => 'd9d67f88-3a97-4784-b4fe-0954aece0a54',
                'id_art_nr' => '0624 B 026',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50101437',
                'ean' => '8714574572192',
                'oem_nr' => '0624 B 026',
                'description' => 'Canon 0624B026/CLI-8PCPM Ink cartridge bundle PC+PM, 2x450 pages 13ml Pack=2',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 20,
                'uuid_id' => 'b99501ed-332e-4f0d-873d-c0296f1181e0',
                'id_art_nr' => '4105615',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50135148',
                'ean' => '4018474105615',
                'oem_nr' => '4105615',
                'description' => 'Pelikan 4105615/C36C37 Ink cartridge multi pack black PGI+CLI, 2x3.425 pages 9ml Pack=2 (replaces Canon CLI-521BK)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 21,
                'uuid_id' => '9668e08e-3223-4d06-a548-f58c2a9ad92f',
                'id_art_nr' => '0263 B 001',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50091097',
                'ean' => '0013803049978',
                'oem_nr' => '0263 B 001',
                'description' => 'Canon 0263B001/FX-9 Toner cartridge black, 2.000 pages',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 22,
                'uuid_id' => '31c29671-9ca6-440c-8061-326ff53e765a',
                'id_art_nr' => '2932 B 012',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50093943',
                'ean' => '8714574564333',
                'oem_nr' => '2932 B 012',
                'description' => 'Canon 2932B012/PGI-520PGBK Ink cartridge black pigmented twin pack, 2x324 pages ISO/IEC 24711 19ml Pack=2',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 23,
                'uuid_id' => 'f63375d6-c1a6-4925-94c6-bd7fc6dd4211',
                'id_art_nr' => '0621 B 029',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50084911',
                'ean' => '8714574552569',
                'oem_nr' => '0621 B 029',
                'description' => 'Canon 0621B029/CLI-8 Ink cartridge multi pack C,M,Y 3x13ml Pack=3',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 24,
                'uuid_id' => '2689d6dd-dc5e-4406-a0ac-6bfe676ef18b',
                'id_art_nr' => '2933 B 010',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50284022',
                'ean' => '8714574630960',
                'oem_nr' => '2933 B 010',
                'description' => 'Canon 2933B010/CLI-521 Ink cartridge multi pack C,M,Y + Photopaper 10x15cm 50 sheet, 3x446 pages ISO/IEC 24711 9ml Pack=3',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 25,
                'uuid_id' => 'd3f41327-28c3-4515-a772-fa7a60c94f87',
                'id_art_nr' => '0621 B 030',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50161143',
                'ean' => '',
                'oem_nr' => '0621 B 030',
                'description' => 'Canon 0621B030/CLI-8GP-501 Ink cartridge multi pack C,M,Y +GP-501 10X15cm 50 sheet 3x13ml Pack=3',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 26,
                'uuid_id' => '5343ff64-3486-4f5b-a15d-719b806debba',
                'id_art_nr' => '4705 A 046',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50165084',
                'ean' => '8714574572147',
                'oem_nr' => '4705 A 046',
                'description' => 'Canon 4705A046/BCI-6BK Ink cartridge black twin pack, 2x210 pages ISO/IEC 24711 13ml Pack=2',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 27,
                'uuid_id' => '74ac3c12-c836-4dfb-bfa2-39a8e25fa3d8',
                'id_art_nr' => '4709 A 018',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50152492',
                'ean' => '8714574572437',
                'oem_nr' => '4709 A 018',
                'description' => 'Canon 4709A018/BCI-6PCPM Ink cartridge multi pack LC,LM, 2x280 pages ISO/IEC 24711 13ml Pack=2',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 28,
                'uuid_id' => 'f855c8aa-ee9a-4e8d-9215-638dba27d8f8',
                'id_art_nr' => '4105684',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50282638',
                'ean' => '4018474105684',
                'oem_nr' => '4105684',
                'description' => 'Pelikan 4105684/C41 Printhead cartridge black, 24 pages 24ml (replaces Canon PG-50)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 29,
                'uuid_id' => 'da54a4e9-f636-4b2d-8940-402a2843f449',
                'id_art_nr' => '361714',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50273086',
                'ean' => '4018474361714',
                'oem_nr' => '361714',
                'description' => 'Pelikan 361714/C29 Ink cartridge magenta, 981 pages 13ml (replaces Canon CLI-8M)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 30,
                'uuid_id' => '24b1d0f6-b74f-4c73-bb20-4f3a265c3c53',
                'id_art_nr' => '359711',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50246119',
                'ean' => '4018474359711',
                'oem_nr' => '359711',
                'description' => 'Pelikan 359711/C26C26 Ink cartridge black pigmented twin pack, 2x593 pages 27ml Pack=2 (replaces Canon PGI-5BK)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 31,
                'uuid_id' => '1c541c4f-4dcf-45a8-a507-31d70fd36971',
                'id_art_nr' => '4107411',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50259095',
                'ean' => '4018474107411',
                'oem_nr' => '4107411',
                'description' => 'Pelikan 4107411/P16 Ink cartridge black pigmented, 593 pages 27ml (replaces Canon PGI-5BK)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 32,
                'uuid_id' => '2641a8dd-7b28-4dcc-9610-bb593d362fc2',
                'id_art_nr' => '0628 B 025',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50071371',
                'ean' => '8714574538518',
                'oem_nr' => '0628 B 025',
                'description' => 'Canon 0628B025/PGI-5BK Ink cartridge black pigmented twin pack, 2x800 pages ISO/IEC 24711 26ml Pack=2',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 33,
                'uuid_id' => '578329ef-eb38-4c35-bdf4-d59883c69144',
                'id_art_nr' => '1510,0003',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50058009',
                'ean' => '4011324151039',
                'oem_nr' => '1510,0003',
                'description' => 'KMP 1510,0003/C74 Ink cartridge cyan, 535 pages ISO/IEC 24711 9ml (replaces Canon CLI-521C)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 34,
                'uuid_id' => '2dd39be1-d7fc-49a6-b741-4b90b60c3ec4',
                'id_art_nr' => '0858,4000',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50062063',
                'ean' => '4011324085822',
                'oem_nr' => '0858,4000',
                'description' => 'KMP 0858,4000/C-T7 Toner cartridge black economy, 2.500 pages/5% 160 grams (replaces Canon FX-3)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 35,
                'uuid_id' => '20cc864a-d9f1-4ef7-bbad-94065f032918',
                'id_art_nr' => '1505,0003',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50049655',
                'ean' => '4011324505030',
                'oem_nr' => '1505,0003',
                'description' => 'KMP 1505,0003/C67 Ink cartridge cyan, 420 pages ISO/IEC 24711 13ml (replaces Canon CLI-8C)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 36,
                'uuid_id' => '5515960e-6314-4f87-93f7-7e47bfee1264',
                'id_art_nr' => '2936 B 001',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50053817',
                'ean' => '4960999577531',
                'oem_nr' => '2936 B 001',
                'description' => 'Canon 2936B001/CLI-521Y Ink cartridge yellow, 477 pages ISO/IEC 24711 205 Photos 9ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 37,
                'uuid_id' => '66df4dd8-6fc2-4521-b712-5b4be23e86f0',
                'id_art_nr' => '2934 B 010',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50054804',
                'ean' => '8714574525808',
                'oem_nr' => '2934 B 010',
                'description' => 'Canon 2934B010/CLI-521 Ink cartridge multi pack C,M,Y, 3x446 pages ISO/IEC 24711 9ml Pack=3',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 38,
                'uuid_id' => '509f7f91-bde4-4b5b-9276-a59e898ac0ad',
                'id_art_nr' => '2934 B 001',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50050848',
                'ean' => '4960999577494',
                'oem_nr' => '2934 B 001',
                'description' => 'Canon 2934B001/CLI-521C Ink cartridge cyan, 448 pages ISO/IEC 24711 205 Photos 9ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 39,
                'uuid_id' => '68551910-5eb2-4175-a4af-07e9c46717ec',
                'id_art_nr' => '1504,0001',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50050865',
                'ean' => '4011324504019',
                'oem_nr' => '1504,0001',
                'description' => 'KMP 1504,0001/C66 Ink cartridge black pigmented, 505 pages ISO/IEC 24711 26ml (replaces Canon PGI-5BK)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 40,
                'uuid_id' => 'cb8edf6d-191d-407c-8b0a-6ca9c9fd334b',
                'id_art_nr' => '1503,0001',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50051035',
                'ean' => '4011324503012',
                'oem_nr' => '1503,0001',
                'description' => 'KMP 1503,0001/C65 Ink cartridge black, 420 pages ISO/IEC 24711 13ml (replaces Canon CLI-8BK)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 41,
                'uuid_id' => '4927a80e-dc5c-4f1e-a62a-fd57eae2c3be',
                'id_art_nr' => '2935 B 001',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50060064',
                'ean' => '4960999577517',
                'oem_nr' => '2935 B 001',
                'description' => 'Canon 2935B001/CLI-521M Ink cartridge magenta, 445 pages ISO/IEC 24711 205 Photos 9ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 42,
                'uuid_id' => 'd1ba1681-19a6-43d7-b466-9a5d7a11c78e',
                'id_art_nr' => '2932 B 001',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50048616',
                'ean' => '4960999577456',
                'oem_nr' => '2932 B 001',
                'description' => 'Canon 2932B001/PGI-520PGBK Ink cartridge black pigmented, 324 pages 19ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 43,
                'uuid_id' => 'a6ddbf5f-0917-4d85-938a-3537d5bbff4e',
                'id_art_nr' => '2933 B 001',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50048748',
                'ean' => '4960999577470',
                'oem_nr' => '2933 B 001',
                'description' => 'Canon 2933B001/CLI-521BK Ink cartridge foto black, 1.250 pages ISO/IEC 24711 690 Photos 9ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 44,
                'uuid_id' => '3de54635-993b-4dc4-b58a-b729d48e93fe',
                'id_art_nr' => '8489 A 002',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50020207',
                'ean' => '4960999201719',
                'oem_nr' => '8489 A 002',
                'description' => 'Canon 8489A002/EP-27 Toner cartridge black, 2.500 pages/5%',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 45,
                'uuid_id' => 'a040d275-4139-4ec1-98ae-6a617fb66c94',
                'id_art_nr' => '7833 A 002',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50017956',
                'ean' => '4960999113494',
                'oem_nr' => '7833 A 002',
                'description' => 'Canon 7833A002/CARTRIDGET Toner cartridge black, 3.500 pages/5%',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 46,
                'uuid_id' => '81fbe46c-df42-47e5-a80c-fd0fcd91390e',
                'id_art_nr' => '339379',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50019850',
                'ean' => '4018474339379',
                'oem_nr' => '339379',
                'description' => 'Pelikan 339379/C18 Ink cartridge black, 370 pages 13ml (replaces Canon BCI-5BK BCI-6BK)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 47,
                'uuid_id' => 'e87299f1-2114-475e-a21b-dbb719c537df',
                'id_art_nr' => '339386',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50019851',
                'ean' => '4018474339386',
                'oem_nr' => '339386',
                'description' => 'Pelikan 339386/C19 Ink cartridge cyan, 440 pages 13ml (replaces Canon BCI-6C)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 48,
                'uuid_id' => 'be3260dc-9f4f-4dee-8955-b527b9ffe40a',
                'id_art_nr' => '339393',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50019852',
                'ean' => '4018474339393',
                'oem_nr' => '339393',
                'description' => 'Pelikan 339393/C20 Ink cartridge magenta, 440 pages 13ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 49,
                'uuid_id' => '4a84b6e4-6bd8-410b-9bd8-c3cfe7ad8c12',
                'id_art_nr' => '339409',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50019853',
                'ean' => '4018474339409',
                'oem_nr' => '339409',
                'description' => 'Pelikan 339409/C21 Ink cartridge yellow, 440 pages 13ml (replaces Canon BCI-6Y)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 50,
                'uuid_id' => '28d74d90-8533-4e48-b6cf-09f631564177',
                'id_art_nr' => '1557 A 020',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50034729',
                'ean' => '',
                'oem_nr' => '1557 A 020',
                'description' => 'Canon 1557A020/FX-3 Toner cartridge black twin pack, 2x2.700 pages/5% Pack=2',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 51,
                'uuid_id' => 'd6999860-bff1-4286-abfa-170e0b25b831',
                'id_art_nr' => '7833 A 008',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50035656',
                'ean' => '8714574981345',
                'oem_nr' => '7833 A 008',
                'description' => 'Canon 7833A008/CARTRIDGET Toner cartridge black twin pack, 2x3.500 pages/5% Pack=2',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 52,
                'uuid_id' => '9b2ec4d9-fe7b-4f5c-9697-b2f55bf2d7ad',
                'id_art_nr' => '0617 B 008',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50033210',
                'ean' => '8714574971384',
                'oem_nr' => '0617 B 008',
                'description' => 'Canon 0617B008/CL-41GP501 Printhead cartridge color +GP-501 10x15cm 100 sheet, 312 pages 12ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 53,
                'uuid_id' => 'c05f7488-0696-46a4-816e-384bff250fb4',
                'id_art_nr' => '0620 B 011',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50033211',
                'ean' => '8714574971391',
                'oem_nr' => '0620 B 011',
                'description' => 'Canon 0620B011/CLI-8PP-101 Ink cartridge multi pack BK,C,M,Y +PP-101 10x15cm 50 sheet 13ml Pack=4',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 54,
                'uuid_id' => '8d6d6fb2-8dce-4ea5-a6e1-855b23210c87',
                'id_art_nr' => '361813',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50066059',
                'ean' => '4018474361813',
                'oem_nr' => '361813',
                'description' => 'Pelikan 361813/P16 Ink cartridge multi pack Bk,C,M,Y, 4x593 pages ISO/IEC 19752 27ml 1 x 27 ml + 3 x 13 ml Pack=4 (replaces Canon CLI-8C CLI-8M CLI-8Y PGI-5BK)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 55,
                'uuid_id' => 'e2a3dd68-fbbf-4bbd-89ee-47c20250df7d',
                'id_art_nr' => '623829',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50023767',
                'ean' => '4018474623829',
                'oem_nr' => '623829',
                'description' => 'Pelikan 623829/1119 Toner cartridge black, 1x5.650 pages 230 grams Pack=1 (replaces Canon CARTRIDGET)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 56,
                'uuid_id' => '4622d7fc-dcc0-451e-9ce3-f2eb114f5797',
                'id_art_nr' => '8955 A 001',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50020943',
                'ean' => '0013803031805',
                'oem_nr' => '8955 A 001',
                'description' => 'Canon 8955A001/FX-8 Toner cartridge black, 3.500 pages',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 57,
                'uuid_id' => 'be318e32-e208-4c8f-9baa-361fdb7a5459',
                'id_art_nr' => '343345',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50026470',
                'ean' => '4018474343345',
                'oem_nr' => '343345',
                'description' => 'Pelikan 343345 Ink cartridge multi pack Bk,C,M,Y Pack=4',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 58,
                'uuid_id' => '9aa5303a-69e9-40e3-abf2-1c88fc021d3e',
                'id_art_nr' => '1557 A 003',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50001415',
                'ean' => '4960999830353',
                'oem_nr' => '1557 A 003',
                'description' => 'Canon 1557A003/FX-3 Toner cartridge black, 2.700 pages/5%',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 59,
                'uuid_id' => 'adac2f7e-7dbb-40fb-bdb2-de785f0a0f91',
                'id_art_nr' => '0985 A 002',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50012263',
                'ean' => '4960999866291',
                'oem_nr' => '0985 A 002',
                'description' => 'Canon 0985A002/BCI-5BK Ink cartridge black, 240 pages 13ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 60,
                'uuid_id' => 'ee389c9d-b395-42c9-9f9a-63cb7f2989dc',
                'id_art_nr' => '0621 B 001',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50027091',
                'ean' => '4960999272672',
                'oem_nr' => '0621 B 001',
                'description' => 'Canon 0621B001/CLI-8C Ink cartridge cyan, 420 pages ISO/IEC 24711 13ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 61,
                'uuid_id' => 'a7633ccb-a192-40ee-a835-e3df6c91ae8f',
                'id_art_nr' => '0622 B 001',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50027092',
                'ean' => '4960999272702',
                'oem_nr' => '0622 B 001',
                'description' => 'Canon 0622B001/CLI-8M Ink cartridge magenta, 478 pages ISO/IEC 24711 13ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 62,
                'uuid_id' => '3156f421-5a4e-48e2-9055-1ee512f4e8ad',
                'id_art_nr' => '0623 B 001',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50027093',
                'ean' => '4960999272825',
                'oem_nr' => '0623 B 001',
                'description' => 'Canon 0623B001/CLI-8Y Ink cartridge yellow, 530 pages ISO/IEC 24711 13ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 63,
                'uuid_id' => 'f4c1af7c-938e-42d5-83ab-3436e8c60b17',
                'id_art_nr' => '0628 B 001',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50027094',
                'ean' => '4960999273020',
                'oem_nr' => '0628 B 001',
                'description' => 'Canon 0628B001/PGI-5BK Ink cartridge black pigmented, 505 pages ISO/IEC 24711 26ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 64,
                'uuid_id' => 'd6ff4dc4-4353-4373-8b64-29695d163efd',
                'id_art_nr' => '0617 B 001',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50027095',
                'ean' => '4960999273433',
                'oem_nr' => '0617 B 001',
                'description' => 'Canon 0617B001/CL-41 Printhead cartridge color, 308 pages ISO/IEC 24711 12ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 65,
                'uuid_id' => 'ca819929-5a29-4481-b0e7-08886de0a28a',
                'id_art_nr' => '0615 B 001',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50027096',
                'ean' => '4960999273372',
                'oem_nr' => '0615 B 001',
                'description' => 'Canon 0615B001/PG-40 Printhead cartridge black 16ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 66,
                'uuid_id' => 'de6e3ba8-3e6d-46af-9260-4eae93585122',
                'id_art_nr' => '0263 B 002',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50027097',
                'ean' => '4960999270616',
                'oem_nr' => '0263 B 002',
                'description' => 'Canon 0263B002/FX-10 Toner cartridge black, 2.000 pages ISO/IEC 19752',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 67,
                'uuid_id' => '6096842c-ac3d-4241-9231-d29e66ab2bfa',
                'id_art_nr' => '0616 B 001',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50027409',
                'ean' => '4960999273402',
                'oem_nr' => '0616 B 001',
                'description' => 'Canon 0616B001/PG-50 Printhead cartridge black 22ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 68,
                'uuid_id' => '4ffe9d7a-cad7-4ceb-9383-cd92521d84fc',
                'id_art_nr' => '1119,0000',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50028593',
                'ean' => '4011324111903',
                'oem_nr' => '1119,0000',
                'description' => 'KMP 1119,0000/C-T14 Toner cartridge black, 3.500 pages/5% (replaces Canon CARTRIDGET)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 69,
                'uuid_id' => '1f21f4e3-ff0e-4722-9757-1704e70bad46',
                'id_art_nr' => '0624 B 001',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50027529',
                'ean' => '4960999272894',
                'oem_nr' => '0624 B 001',
                'description' => 'Canon 0624B001/CLI-8PC Ink cartridge light cyan, 5.715 pages 13ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 70,
                'uuid_id' => '398bfa5c-ac03-4072-88f9-45cc3a1448ca',
                'id_art_nr' => '0625 B 001',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50027530',
                'ean' => '4960999272931',
                'oem_nr' => '0625 B 001',
                'description' => 'Canon 0625B001/CLI-8PM Ink cartridge light magenta, 5.630 pages 13ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 71,
                'uuid_id' => 'a67a5bf9-41ce-4716-870b-d37ba09d4aeb',
                'id_art_nr' => '1176,0000',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50030979',
                'ean' => '4011324117608',
                'oem_nr' => '1176,0000',
                'description' => 'KMP 1176,0000/C-T15 Toner cartridge black, 2.000 pages 130 grams (replaces Canon FX-10)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 72,
                'uuid_id' => '6273addc-000b-488e-a0ab-5882837f8405',
                'id_art_nr' => '1121,0000',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50030980',
                'ean' => '4011324112108',
                'oem_nr' => '1121,0000',
                'description' => 'KMP 1121,0000/C-T16 Toner cartridge black, 2.500 pages/5% (replaces Canon EP-27)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 73,
                'uuid_id' => '6cade6ea-52f4-4e9b-b09b-a29bc73fa170',
                'id_art_nr' => '4706 A 022',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50028832',
                'ean' => '8714574959580',
                'oem_nr' => '4706 A 022',
                'description' => 'Canon 4706A022/BCI-6 Ink cartridge multi pack C,M,Y, 3x280 pages ISO/IEC 24711 3x13ml Pack=3',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 74,
                'uuid_id' => '7820532e-b2e5-4992-ae20-5db2069ca5e9',
                'id_art_nr' => '4706 A 027',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50038802',
                'ean' => '8714574987408',
                'oem_nr' => '4706 A 027',
                'description' => 'Canon 4706A027/BCI-6 Ink cartridge multi pack C,M,Y + Paper SG-101 3x13ml Pack=3',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 75,
                'uuid_id' => '66045a09-10bd-4e4c-af1f-5c5ca3f76936',
                'id_art_nr' => '1500,HC01',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50041342',
                'ean' => '4011324150025',
                'oem_nr' => '1500,HC01',
                'description' => 'KMP 1500,HC01/C59 Ink cartridge black, 300 pages 22ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 76,
                'uuid_id' => '3b23ca2e-aa7a-485c-b589-81e50ff4bbbd',
                'id_art_nr' => '1500,4001',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50041343',
                'ean' => '4011324150018',
                'oem_nr' => '1500,4001',
                'description' => 'KMP 1500,4001/C57 Ink cartridge black, 195 pages 16ml (replaces Canon PG-40)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 77,
                'uuid_id' => '6e00d7aa-ccf0-4def-b4f0-38c47f6ee239',
                'id_art_nr' => '1501,4030',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50041345',
                'ean' => '4011324150117',
                'oem_nr' => '1501,4030',
                'description' => 'KMP 1501,4030/C58 Ink cartridge color, 155 pages ISO/IEC 24711 3ml (replaces Canon CL-41)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 78,
                'uuid_id' => 'efc5d7fd-9629-4838-955d-a94560c8e91b',
                'id_art_nr' => '358844',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50036943',
                'ean' => '4018474358844',
                'oem_nr' => '358844',
                'description' => 'Pelikan 358844/C26P Ink cartridge black pigmented Power-Pad 24ml Pack=3 (replaces Canon PGI-5BK)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 79,
                'uuid_id' => '8c1016dc-ec10-46a5-b4b4-e0aec07a7082',
                'id_art_nr' => '358851',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50036944',
                'ean' => '4018474358851',
                'oem_nr' => '358851',
                'description' => 'Pelikan 358851/C27P Power-Pads black 4.5ml Pack=3 (replaces Canon CLI-8BK)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 80,
                'uuid_id' => '4cb0f322-c061-4a98-8751-0a0ed402ae75',
                'id_art_nr' => '358868',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50036945',
                'ean' => '4018474358868',
                'oem_nr' => '358868',
                'description' => 'Pelikan 358868/C31P Ink cartridge multi pack cyan magenta yellow Power-Pad 4.5ml Pack=9 (replaces Canon CLI-8C)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 81,
                'uuid_id' => '008b17c3-bf4a-471a-9664-5cb40433da1e',
                'id_art_nr' => '0621 B 015',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50041747',
                'ean' => '8714574504681',
                'oem_nr' => '0621 B 015',
                'description' => 'Canon 0621B015/CLI-8GP-501 Ink cartridge multi pack C,M,Y + Paper GP-501 3x13ml Pack=3',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 82,
                'uuid_id' => '66b9bcbb-61dd-4ed2-abf6-d8a90ab4ce42',
                'id_art_nr' => '4708 A 002',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50014291',
                'ean' => '4960999864761',
                'oem_nr' => '4708 A 002',
                'description' => 'Canon 4708A002/BCI-6Y Ink cartridge yellow, 210 pages/5% 13ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 83,
                'uuid_id' => '713381fc-e5f5-4b34-917c-1b286ab6c725',
                'id_art_nr' => '4707 A 002',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50014292',
                'ean' => '4960999864792',
                'oem_nr' => '4707 A 002',
                'description' => 'Canon 4707A002/BCI-6M Ink cartridge magenta, 280 pages ISO/IEC 24711 13ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 84,
                'uuid_id' => 'c22a6880-babc-47f5-8fd8-168cea9ccf97',
                'id_art_nr' => '4706 A 002',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50014293',
                'ean' => '4960999864822',
                'oem_nr' => '4706 A 002',
                'description' => 'Canon 4706A002/BCI-6C Ink cartridge cyan, 280 pages ISO/IEC 24711 13ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 85,
                'uuid_id' => '63d26805-cdf6-4f48-8800-a841a9829044',
                'id_art_nr' => '4705 A 002',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50014294',
                'ean' => '4960999864853',
                'oem_nr' => '4705 A 002',
                'description' => 'Canon 4705A002/BCI-6BK Ink cartridge black, 210 pages ISO/IEC 24711 13ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 86,
                'uuid_id' => 'ae3eb091-02ca-4e74-a1c2-c6cb5944e2be',
                'id_art_nr' => '4709 A 002',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50014516',
                'ean' => '4960999864730',
                'oem_nr' => '4709 A 002',
                'description' => 'Canon 4709A002/BCI-6PC Ink cartridge light cyan, 280 pages ISO/IEC 24711 13ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 87,
                'uuid_id' => '77100d89-afd4-42e4-a088-a7971321b5de',
                'id_art_nr' => '4710 A 002',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50014517',
                'ean' => '4960999864709',
                'oem_nr' => '4710 A 002',
                'description' => 'Canon 4710A002/BCI-6PM Ink cartridge light magenta, 280 pages ISO/IEC 24711 13ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 88,
                'uuid_id' => '91c6ce7d-d084-41dc-95db-274011e34810',
                'id_art_nr' => '0958,0001',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50013796',
                'ean' => '4011324958010',
                'oem_nr' => '0958,0001',
                'description' => 'KMP 0958,0001/C15 Ink cartridge black, 210 pages ISO/IEC 24711 17ml (replaces Canon BCI-6BK)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 89,
                'uuid_id' => '56376731-9b37-485d-9366-c185978a29ba',
                'id_art_nr' => '0958,0003',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50013797',
                'ean' => '4011324958034',
                'oem_nr' => '0958,0003',
                'description' => 'KMP 0958,0003/C16 Ink cartridge cyan, 280 pages ISO/IEC 24711 17ml (replaces Canon BCI-6C)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 90,
                'uuid_id' => '928ccac5-70f8-41d7-a3d4-bb2b6dc1b5f4',
                'id_art_nr' => '0958,0006',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50013798',
                'ean' => '4011324958065',
                'oem_nr' => '0958,0006',
                'description' => 'KMP 0958,0006/C17 Ink cartridge magenta, 280 pages ISO/IEC 24711 17ml (replaces Canon BCI-6M)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 91,
                'uuid_id' => '984db026-02e5-44da-aa92-3dc39bf27b68',
                'id_art_nr' => '0958,0009',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50013799',
                'ean' => '4011324958096',
                'oem_nr' => '0958,0009',
                'description' => 'KMP 0958,0009/C18 Ink cartridge yellow, 280 pages ISO/IEC 24711 17ml (replaces Canon BCI-6Y)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 92,
                'uuid_id' => 'f8b5d5b6-84a5-4a94-abc0-fab6a529eaa2',
                'id_art_nr' => '0958,0043',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50013800',
                'ean' => '4011324958430',
                'oem_nr' => '0958,0043',
                'description' => 'KMP 0958,0043/C19 Ink cartridge light cyan 17ml (replaces Canon BCI-6PC)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 93,
                'uuid_id' => 'e4f48c4a-88f7-4470-9b29-85d222237b6d',
                'id_art_nr' => '0958,0046',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50013801',
                'ean' => '4011324958461',
                'oem_nr' => '0958,0046',
                'description' => 'KMP 0958,0046/C20 Ink cartridge light magenta 17ml (replaces Canon BCI-6PM)',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 94,
                'uuid_id' => '8da142db-f2b8-4e3e-aedd-b38c54c07674',
                'id_art_nr' => '0620 B 001',
                'id_reseller' => 'Bechlem Demo',
                'id_item' => '50027090',
                'ean' => '4960999273235',
                'oem_nr' => '0620 B 001',
                'description' => 'Canon 0620B001/CLI-8BK Ink cartridge black, 400 pages ISO/IEC 24711 13ml',
                've' => '',
                'language' => 'en',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
        ];

        $table = $this->table('bechlem_reseller_items');
        $table->insert($data)->save();
    }
}
