<?php
declare(strict_types=1);

/* 
 * MIT License
 *
 * Copyright (c) 2018-present, Marks Software GmbH (https://www.marks-software.de/)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
use Cake\I18n\DateTime;
use Migrations\AbstractSeed;

/**
 * BechlemBrands seed.
 */
class BechlemBrandsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     *
     * @return void
     */
    public function run(): void
    {
        $dateTime = DateTime::now();

        $data = [
            [
                'id' => 1,
                'uuid_id' => '9bc3b386-1bb8-4202-905a-4723a1ea79d4',
                'id_brand' => '20002769',
                'name' => 'Sindoh',
                'upper_name' => 'SINDOH',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 2,
                'uuid_id' => 'f0305838-8623-4352-9534-f51940d44ce5',
                'id_brand' => '20000969',
                'name' => 'Microplex',
                'upper_name' => 'MICROPLEX',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 3,
                'uuid_id' => 'd1a521b2-d847-4a25-8977-10db693064f3',
                'id_brand' => '20000984',
                'name' => 'Kyocera',
                'upper_name' => 'KYOCERA',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 4,
                'uuid_id' => 'aba3c281-67da-41dc-b8cd-a2ee004336b1',
                'id_brand' => '20000989',
                'name' => 'Mitsubishi',
                'upper_name' => 'MITSUBISHI',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 5,
                'uuid_id' => 'b7f91a64-56ed-455b-9985-1e1f7aee2b67',
                'id_brand' => '20000243',
                'name' => 'Bull',
                'upper_name' => 'BULL',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 6,
                'uuid_id' => '49ecdabc-0374-4238-9643-f87ba7676667',
                'id_brand' => '20000246',
                'name' => 'Burroughs',
                'upper_name' => 'BURROUGHS',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 7,
                'uuid_id' => '52b25b5b-168c-4e1f-ae05-fdbb91cc0336',
                'id_brand' => '20000252',
                'name' => 'C.Itoh',
                'upper_name' => 'C.ITOH',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 8,
                'uuid_id' => '278a3a47-27ab-49a0-b1ab-eac2c32328a4',
                'id_brand' => '20000264',
                'name' => 'Canon',
                'upper_name' => 'CANON',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 9,
                'uuid_id' => '2b274477-5660-4242-9cfc-2f170e4e6648',
                'id_brand' => '20000276',
                'name' => 'Casio',
                'upper_name' => 'CASIO',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 10,
                'uuid_id' => '301e1cf2-9990-480a-8f94-9e096a153e34',
                'id_brand' => '20001279',
                'name' => 'Seiko Precision',
                'upper_name' => 'SEIKO PRECISION',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 11,
                'uuid_id' => '5be71077-9c7a-4514-8d2d-a22aabd12e71',
                'id_brand' => '20001280',
                'name' => 'Seikosha',
                'upper_name' => 'SEIKOSHA',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 12,
                'uuid_id' => 'ea6d9598-fefb-4f1f-b257-b3e278e36f4f',
                'id_brand' => '20001284',
                'name' => 'Selex',
                'upper_name' => 'SELEX',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 13,
                'uuid_id' => '40d16827-990b-431b-a8c6-ad1f097f681d',
                'id_brand' => '20001289',
                'name' => 'Sharp',
                'upper_name' => 'SHARP',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 14,
                'uuid_id' => 'dd7e4705-6828-4c8b-934e-7f7397a96d95',
                'id_brand' => '20000784',
                'name' => 'Infotec',
                'upper_name' => 'INFOTEC',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 15,
                'uuid_id' => '14694a36-ca39-4648-bb21-14907e0149e9',
                'id_brand' => '20001047',
                'name' => 'Nokia',
                'upper_name' => 'NOKIA',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 16,
                'uuid_id' => '52946021-a19b-4683-9acb-b6a540830f6f',
                'id_brand' => '20000302',
                'name' => 'Citizen',
                'upper_name' => 'CITIZEN',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 17,
                'uuid_id' => 'bfbbbcac-b1c7-43c2-877f-4a001f8d33a2',
                'id_brand' => '20000329',
                'name' => 'Commodore',
                'upper_name' => 'COMMODORE',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 18,
                'uuid_id' => '91ba3c9a-6a3d-45d0-972f-3fc31df85048',
                'id_brand' => '20000333',
                'name' => 'Compaq',
                'upper_name' => 'COMPAQ',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 19,
                'uuid_id' => '2d54ca22-f6de-4df9-af68-77609331898e',
                'id_brand' => '20000344',
                'name' => 'Compuprint',
                'upper_name' => 'COMPUPRINT',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 20,
                'uuid_id' => 'b5c785c9-ea35-401a-a243-6f2bf6525636',
                'id_brand' => '20000054',
                'name' => 'Agfa',
                'upper_name' => 'AGFA',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 21,
                'uuid_id' => 'b322dd51-a8d9-4457-bdbd-8185008bb762',
                'id_brand' => '20000063',
                'name' => 'Alcatel',
                'upper_name' => 'ALCATEL',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 22,
                'uuid_id' => 'd80a08cf-cfe3-44e2-b994-c3cf5fe896d6',
                'id_brand' => '20000068',
                'name' => 'Nakajima',
                'upper_name' => 'NAKAJIMA',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 23,
                'uuid_id' => '15e5f38f-474c-46e0-b937-ab5cc1a02667',
                'id_brand' => '20000080',
                'name' => 'Alps',
                'upper_name' => 'ALPS',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 24,
                'uuid_id' => '55aa4005-85bd-4737-8a46-72426b1b5f82',
                'id_brand' => '20000098',
                'name' => 'Amstrad',
                'upper_name' => 'AMSTRAD',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 25,
                'uuid_id' => '05a74d7d-ffdc-454d-9180-be56d611d4d9',
                'id_brand' => '20001295',
                'name' => 'Wincor-Nixdorf',
                'upper_name' => 'WINCOR-NIXDORF',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 26,
                'uuid_id' => 'a3b1538b-e09f-4df8-87ad-d24af6a0079a',
                'id_brand' => '20001299',
                'name' => 'Silver Reed',
                'upper_name' => 'SILVER REED',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'COM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 27,
                'uuid_id' => 'f0853849-89d0-47ba-9c81-dd091e2b4adc',
                'id_brand' => '20001305',
                'name' => 'Smith Corona',
                'upper_name' => 'SMITH CORONA',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 28,
                'uuid_id' => '82205a73-6109-43d4-99ed-5eef81ddef41',
                'id_brand' => '20001311',
                'name' => 'Sony',
                'upper_name' => 'SONY',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 29,
                'uuid_id' => '5c0ca1d9-cdbf-41f9-8b8c-3a086cf7bb61',
                'id_brand' => '20001328',
                'name' => 'Star Micronics',
                'upper_name' => 'STAR MICRONICS',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 30,
                'uuid_id' => 'b15ccd6d-440a-4cd4-8613-1e0d89cfdab2',
                'id_brand' => '20001348',
                'name' => 'Swintec',
                'upper_name' => 'SWINTEC',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 31,
                'uuid_id' => 'b92da2d6-2e30-40af-9eba-9841c5da408a',
                'id_brand' => '20000827',
                'name' => 'Jetfax',
                'upper_name' => 'JETFAX',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 32,
                'uuid_id' => '0ecaeae0-d44e-4152-a967-c7baaa6c9ca6',
                'id_brand' => '20000101',
                'name' => 'Anadex',
                'upper_name' => 'ANADEX',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 33,
                'uuid_id' => 'efbfd2d0-a5e1-4a54-8ff7-b7c5923ad576',
                'id_brand' => '20001067',
                'name' => 'OCE',
                'upper_name' => 'OCE',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 34,
                'uuid_id' => 'ee0fbf58-e12c-4801-b23a-2d4818aed6a3',
                'id_brand' => '20001074',
                'name' => 'OKI',
                'upper_name' => 'OKI',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 35,
                'uuid_id' => 'c65dd296-b023-4bf1-b0da-60f63adf0584',
                'id_brand' => '20001076',
                'name' => 'Olivetti',
                'upper_name' => 'OLIVETTI',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 36,
                'uuid_id' => '90feaae8-ea7b-4f91-abb9-032afeb354e6',
                'id_brand' => '20001077',
                'name' => 'Olympia',
                'upper_name' => 'OLYMPIA',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 37,
                'uuid_id' => '7d2662e0-561d-41c9-99bf-cbbe7fb82a51',
                'id_brand' => '20001079',
                'name' => 'Omnifax',
                'upper_name' => 'OMNIFAX',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 38,
                'uuid_id' => '29265708-dac0-4592-93aa-3c6f6241e3e3',
                'id_brand' => '20001080',
                'name' => 'Omron',
                'upper_name' => 'OMRON',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 39,
                'uuid_id' => '4336ff77-82da-45e9-8d82-d4e3bb1847b9',
                'id_brand' => '20001086',
                'name' => 'OTC',
                'upper_name' => 'OTC',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 40,
                'uuid_id' => '343b5ee8-aba3-492c-b61f-ef03ccd93379',
                'id_brand' => '20001099',
                'name' => 'Panasonic',
                'upper_name' => 'PANASONIC',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 41,
                'uuid_id' => '75c88411-7116-49a1-826b-e37e20ce0920',
                'id_brand' => '20000120',
                'name' => 'Apple',
                'upper_name' => 'APPLE',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 42,
                'uuid_id' => '69417476-bd9d-4854-ac40-63e72ebb239c',
                'id_brand' => '20000841',
                'name' => 'Kentek',
                'upper_name' => 'KENTEK',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 43,
                'uuid_id' => 'a446b244-1d20-487a-941f-73df1dfee42f',
                'id_brand' => '20000849',
                'name' => 'KMP',
                'upper_name' => 'KMP',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'COM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 44,
                'uuid_id' => '7f09e2b9-e37d-4682-8a0b-6cfbadccf812',
                'id_brand' => '20000851',
                'name' => 'Kodak',
                'upper_name' => 'KODAK',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 45,
                'uuid_id' => '92a43158-1843-443f-998c-c0de10fb623b',
                'id_brand' => '20000861',
                'name' => 'Lanier',
                'upper_name' => 'LANIER',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 46,
                'uuid_id' => 'aa6de95d-c357-4d0c-be9c-816d389974ff',
                'id_brand' => '20001109',
                'name' => 'Pelikan',
                'upper_name' => 'PELIKAN',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'COM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 47,
                'uuid_id' => '179a3506-b2db-41cf-a3ab-30e86d6fc0c3',
                'id_brand' => '20000388',
                'name' => 'COT',
                'upper_name' => 'COT',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 48,
                'uuid_id' => '176ad632-b7c1-40dd-ae0b-7cbe4f8545d7',
                'id_brand' => '20000391',
                'name' => 'CPF',
                'upper_name' => 'CPF',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 49,
                'uuid_id' => '738af8d8-c380-4910-878f-e4bedc649a90',
                'id_brand' => '20001476',
                'name' => 'Unisys',
                'upper_name' => 'UNISYS',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 50,
                'uuid_id' => '54bfc3fc-9dd1-4476-b4a5-12f17f81be8e',
                'id_brand' => '20000681',
                'name' => 'Gestetner',
                'upper_name' => 'GESTETNER',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 51,
                'uuid_id' => '8e5733b7-f226-400c-892a-03cda122596c',
                'id_brand' => '20000946',
                'name' => 'Memorex',
                'upper_name' => 'MEMOREX',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 52,
                'uuid_id' => 'a667078e-0e6d-43aa-a23f-cb69d4e85839',
                'id_brand' => '20000499',
                'name' => 'Dell',
                'upper_name' => 'DELL',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 53,
                'uuid_id' => '53de77f6-4edf-4494-8a32-10eb43b9fd1b',
                'id_brand' => '20000511',
                'name' => 'Detewe',
                'upper_name' => 'DETEWE',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 54,
                'uuid_id' => '0c769936-b084-493b-8260-b49dd191dfd1',
                'id_brand' => '20000513',
                'name' => 'Develop',
                'upper_name' => 'DEVELOP',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 55,
                'uuid_id' => '73dc30a0-b679-4a40-9194-920c7bdddd10',
                'id_brand' => '20000515',
                'name' => 'Diablo',
                'upper_name' => 'DIABLO',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 56,
                'uuid_id' => 'aab97c0a-10a9-4e5c-b837-d6e18a3645b8',
                'id_brand' => '20000530',
                'name' => 'Digital Equipment Corp',
                'upper_name' => 'DIGITAL EQUIPMENT CORP',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 57,
                'uuid_id' => '72a3fd4c-6300-4bc9-b808-18cf33c22034',
                'id_brand' => '20000746',
                'name' => 'IBM',
                'upper_name' => 'IBM',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 58,
                'uuid_id' => 'a7125117-29f6-421b-9d10-09a3b6ac9cce',
                'id_brand' => '20000750',
                'name' => 'ICL',
                'upper_name' => 'ICL',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 59,
                'uuid_id' => 'e22fab76-02f9-4531-8bc7-f1cb779eb72d',
                'id_brand' => '20000037',
                'name' => 'Adler-Royal',
                'upper_name' => 'ADLER-ROYAL',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 60,
                'uuid_id' => '106f4997-f9ea-4cb0-b309-d960a07b25e9',
                'id_brand' => '20000999',
                'name' => 'Monroe',
                'upper_name' => 'MONROE',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 61,
                'uuid_id' => 'c52c9ba3-b512-4e0b-aaff-7c0b0df6db1d',
                'id_brand' => '20001003',
                'name' => 'Motorola',
                'upper_name' => 'MOTOROLA',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 62,
                'uuid_id' => 'ccb2492f-b1bd-4d46-a9ee-e9c1ea58691c',
                'id_brand' => '20001013',
                'name' => 'Muratec',
                'upper_name' => 'MURATEC',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 63,
                'uuid_id' => '86583346-d476-4ebe-93db-e76237f1fcc4',
                'id_brand' => '20001484',
                'name' => 'Utax',
                'upper_name' => 'UTAX',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 64,
                'uuid_id' => '7f727e23-d2b3-43cd-b536-a80b39298aba',
                'id_brand' => '20000002',
                'name' => '3 M',
                'upper_name' => '3 M',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 65,
                'uuid_id' => 'a742ec6e-1626-452b-b266-31df50ee0755',
                'id_brand' => '20000004',
                'name' => 'A.B. Dick',
                'upper_name' => 'A.B. DICK',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 66,
                'uuid_id' => 'f97adbf0-134f-42d3-a3dc-eeb5fb3dae9b',
                'id_brand' => '20001026',
                'name' => 'NCR',
                'upper_name' => 'NCR',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 67,
                'uuid_id' => '6682d805-1963-45ff-ad5e-5f2091b2bbf3',
                'id_brand' => '20001029',
                'name' => 'NEC',
                'upper_name' => 'NEC',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 68,
                'uuid_id' => '181f14d3-38dd-462a-9ad0-f3a6ef70c5c5',
                'id_brand' => '20001237',
                'name' => 'Sagem',
                'upper_name' => 'SAGEM',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 69,
                'uuid_id' => 'f3a896f2-3698-4b24-b4d0-97eec4e0e0ca',
                'id_brand' => '20001240',
                'name' => 'Samsung',
                'upper_name' => 'SAMSUNG',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 70,
                'uuid_id' => '3e535e9a-d05e-46fc-8506-8bf6902b18cc',
                'id_brand' => '20001250',
                'name' => 'Sanyo',
                'upper_name' => 'SANYO',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 71,
                'uuid_id' => '722e90cc-501e-4aaa-ab26-b0b00d7bd3f4',
                'id_brand' => '20001257',
                'name' => 'Savin',
                'upper_name' => 'SAVIN',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 72,
                'uuid_id' => '9acf60d0-b209-432a-b35c-91c421248587',
                'id_brand' => '20001511',
                'name' => 'Wang',
                'upper_name' => 'WANG',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 73,
                'uuid_id' => '24e9b40f-6e24-4e9f-a5e4-fb7fb29ea9df',
                'id_brand' => '20001535',
                'name' => 'Xerox',
                'upper_name' => 'XEROX',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 74,
                'uuid_id' => '4b64189b-2172-4f29-bf29-b6d98628c4bb',
                'id_brand' => '20000728',
                'name' => 'HP',
                'upper_name' => 'HP',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 75,
                'uuid_id' => '13189b84-0e6f-45f0-b766-0a815deef9ab',
                'id_brand' => '20000730',
                'name' => 'Hitachi',
                'upper_name' => 'HITACHI',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 76,
                'uuid_id' => '3a786eae-e002-47a3-b9c4-cb031777a4c0',
                'id_brand' => '20000569',
                'name' => 'EGT',
                'upper_name' => 'EGT',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 77,
                'uuid_id' => '725b3e47-a4c4-4f45-a343-1f7e8c24caf3',
                'id_brand' => '20000586',
                'name' => 'Encad',
                'upper_name' => 'ENCAD',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 78,
                'uuid_id' => '773d4475-31d2-4871-aeb2-2c9494a1cd7b',
                'id_brand' => '20000593',
                'name' => 'Epson',
                'upper_name' => 'EPSON',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 79,
                'uuid_id' => 'a51cc4f7-ccc6-4635-b01f-af75347972d6',
                'id_brand' => '20001602',
                'name' => 'Danka',
                'upper_name' => 'DANKA',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 80,
                'uuid_id' => '4e13740a-4e8d-42f5-a605-2ef6b173e4ff',
                'id_brand' => '20001605',
                'name' => 'Tenovis',
                'upper_name' => 'TENOVIS',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 81,
                'uuid_id' => '4b10b4e9-e107-45f0-a4f9-6995612057c4',
                'id_brand' => '20001607',
                'name' => 'Primera',
                'upper_name' => 'PRIMERA',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 82,
                'uuid_id' => '035c48f0-34d4-40aa-bac0-82101a19d361',
                'id_brand' => '20001612',
                'name' => 'Copystar',
                'upper_name' => 'COPYSTAR',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 83,
                'uuid_id' => '845cb729-2d3d-47a6-b317-03fafbad874a',
                'id_brand' => '20001648',
                'name' => 'Quadient',
                'upper_name' => 'QUADIENT',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 84,
                'uuid_id' => 'c6699bf6-21c0-46dc-85d6-6ff911510e79',
                'id_brand' => '20001768',
                'name' => 'Imagistics',
                'upper_name' => 'IMAGISTICS',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 85,
                'uuid_id' => 'b0fe750f-6ded-4922-9886-c7d05b0f8cad',
                'id_brand' => '20001122',
                'name' => 'Philips',
                'upper_name' => 'PHILIPS',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 86,
                'uuid_id' => '2bc8179d-d0a2-44cd-8ebe-f6a843aae813',
                'id_brand' => '20001128',
                'name' => 'Pitney Bowes',
                'upper_name' => 'PITNEY BOWES',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 87,
                'uuid_id' => '97301ab9-6ac1-4071-82fe-18a3b1dd5fef',
                'id_brand' => '20001145',
                'name' => 'Xante',
                'upper_name' => 'XANTE',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 88,
                'uuid_id' => '199236dc-b803-43dc-94f0-425c9fba2d76',
                'id_brand' => '20001150',
                'name' => 'Printronix',
                'upper_name' => 'PRINTRONIX',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 89,
                'uuid_id' => '2da90d33-cf47-42f6-b995-36df0b13ecc1',
                'id_brand' => '20001154',
                'name' => 'Privileg',
                'upper_name' => 'PRIVILEG',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 90,
                'uuid_id' => 'bfaf8c80-a354-4468-a29e-8da3c988450f',
                'id_brand' => '20002389',
                'name' => 'NRG',
                'upper_name' => 'NRG',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 91,
                'uuid_id' => '0be73d53-0d34-4a25-bbb2-971b51f46ec1',
                'id_brand' => '20002488',
                'name' => 'Dymo',
                'upper_name' => 'DYMO',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 92,
                'uuid_id' => '557e7ccd-8446-4482-ae15-b9b02f22ded8',
                'id_brand' => '20002568',
                'name' => 'Infoprint Solutions Company',
                'upper_name' => 'INFOPRINT SOLUTIONS COMPANY',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 93,
                'uuid_id' => '5c9bb852-f92e-4097-9300-692f35b64ecd',
                'id_brand' => '20001161',
                'name' => 'PSI',
                'upper_name' => 'PSI',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 94,
                'uuid_id' => '3c3ded6f-d532-4f94-a1df-a136a62171f2',
                'id_brand' => '20001164',
                'name' => 'Konica Minolta',
                'upper_name' => 'KONICA MINOLTA',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 95,
                'uuid_id' => 'fd9fd117-0ca5-4862-8424-7d620b689986',
                'id_brand' => '20001383',
                'name' => 'TEC',
                'upper_name' => 'TEC',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 96,
                'uuid_id' => 'b4135dbb-db90-4fbe-a91b-8fd5c74f4c84',
                'id_brand' => '20001400',
                'name' => 'Telekom',
                'upper_name' => 'TELEKOM',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 97,
                'uuid_id' => '8daf780e-c914-4f80-bcfd-c6f9a6a2b418',
                'id_brand' => '20001405',
                'name' => 'Telesystems',
                'upper_name' => 'TELESYSTEMS',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 98,
                'uuid_id' => 'ad79a99f-552a-45f8-b933-26333812fccb',
                'id_brand' => '20000204',
                'name' => 'Binder',
                'upper_name' => 'BINDER',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 99,
                'uuid_id' => 'addf3d11-22e2-439f-97b7-0cdfbabfe8db',
                'id_brand' => '20000218',
                'name' => 'Bosch',
                'upper_name' => 'BOSCH',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 100,
                'uuid_id' => 'ef74774d-e78c-4eec-9d65-3f1fae439f69',
                'id_brand' => '20000623',
                'name' => 'Facit',
                'upper_name' => 'FACIT',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 101,
                'uuid_id' => 'a39c927d-742d-4e21-bf9b-50845435355b',
                'id_brand' => '20000868',
                'name' => 'Lasermaster',
                'upper_name' => 'LASERMASTER',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 102,
                'uuid_id' => 'd58bd56f-62a5-4106-a42e-22f05eff9703',
                'id_brand' => '20000886',
                'name' => 'Lexmark',
                'upper_name' => 'LEXMARK',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 103,
                'uuid_id' => '6be16b6e-8a2a-47af-a581-31402acc4a01',
                'id_brand' => '20000228',
                'name' => 'British Telecom',
                'upper_name' => 'BRITISH TELECOM',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 104,
                'uuid_id' => '2df87449-dead-45d5-a422-7930e35d0fbd',
                'id_brand' => '20000229',
                'name' => 'Brother',
                'upper_name' => 'BROTHER',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 105,
                'uuid_id' => 'ad70385e-7f3a-4333-b0bd-a69735611c75',
                'id_brand' => '20000471',
                'name' => 'Dataproducts',
                'upper_name' => 'DATAPRODUCTS',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 106,
                'uuid_id' => 'c9c4f10f-acee-48cc-b146-5415a0839d13',
                'id_brand' => '20001196',
                'name' => 'Regma',
                'upper_name' => 'REGMA',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 107,
                'uuid_id' => 'f6e173d8-c1c0-4017-8994-55e6c96a8130',
                'id_brand' => '20001207',
                'name' => 'Rena',
                'upper_name' => 'RENA',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 108,
                'uuid_id' => 'a32e6694-d278-4148-86d1-8ae1c9dfd598',
                'id_brand' => '20001210',
                'name' => 'Rex Rotary',
                'upper_name' => 'REX ROTARY',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 109,
                'uuid_id' => 'e3e9c0f9-691e-4981-904c-9f95abc3a8c7',
                'id_brand' => '20000652',
                'name' => 'Fujitsu',
                'upper_name' => 'FUJITSU',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 110,
                'uuid_id' => '9da986ea-2e84-482e-9e4d-a6da27c4eab7',
                'id_brand' => '20000653',
                'name' => 'Fujitsu General',
                'upper_name' => 'FUJITSU GENERAL',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 111,
                'uuid_id' => '26ac06c6-d37c-4903-ab45-51e0dafa8316',
                'id_brand' => '20000662',
                'name' => 'GCC',
                'upper_name' => 'GCC',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 112,
                'uuid_id' => '39973a87-ae6b-400b-9f29-f53a32e8e4a4',
                'id_brand' => '20001421',
                'name' => 'Texas Instruments',
                'upper_name' => 'TEXAS INSTRUMENTS',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 113,
                'uuid_id' => '85280e84-9b6c-4c42-b65a-0e7c481335e7',
                'id_brand' => '20001988',
                'name' => 'Riso',
                'upper_name' => 'RISO',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 114,
                'uuid_id' => 'cbca72c6-67de-4f06-9095-12afb44d9743',
                'id_brand' => '20000920',
                'name' => 'Tally Genicom',
                'upper_name' => 'TALLY GENICOM',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 115,
                'uuid_id' => '58316983-42af-4c35-86b9-77da1fa1bb4e',
                'id_brand' => '20001214',
                'name' => 'Ricoh',
                'upper_name' => 'RICOH',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 116,
                'uuid_id' => '1643fb4d-4454-4407-839c-dafdcd43679e',
                'id_brand' => '20001218',
                'name' => 'Roland',
                'upper_name' => 'ROLAND',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 117,
                'uuid_id' => '962397c5-7287-4bde-87ac-4403073e0a83',
                'id_brand' => '20001434',
                'name' => 'Toshiba',
                'upper_name' => 'TOSHIBA',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 118,
                'uuid_id' => 'bbc04215-efad-45bf-aae5-8044bb73a6bd',
                'id_brand' => '20001453',
                'name' => 'Triumph-Adler',
                'upper_name' => 'TRIUMPH-ADLER',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 119,
                'uuid_id' => '2ba2427a-b5bd-49ae-828d-367265fd18fd',
                'id_brand' => '50101833',
                'name' => 'Dascom',
                'upper_name' => 'DASCOM',
                'id_par_brand' => '',
                'importance' => '2',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 120,
                'uuid_id' => '37e6eca4-73d3-442c-a651-269530abd2ef',
                'id_brand' => '50096914',
                'name' => 'Pantum',
                'upper_name' => 'PANTUM',
                'id_par_brand' => '',
                'importance' => '1',
                'type' => 'OEM',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
        ];

        $table = $this->table('bechlem_brands');
        $table->insert($data)->save();
    }
}
