<?php
declare(strict_types=1);

/* 
 * MIT License
 *
 * Copyright (c) 2018-present, Marks Software GmbH (https://www.marks-software.de/)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
use Cake\I18n\DateTime;
use Cake\Utility\Text;
use Migrations\AbstractSeed;

/**
 * ProductManufacturers seed.
 */
class ProductManufacturersSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     *
     * @return void
     */
    public function run(): void
    {
        $dateTime = DateTime::now();

        $data = [
            [
                'id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000002',
                'name' => '3M',
                'slug' => '3m',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 2,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000004',
                'name' => 'A.B. Dick',
                'slug' => 'a-b-dick',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 3,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000037',
                'name' => 'Adler-Royal',
                'slug' => 'adler-royal',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 4,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000054',
                'name' => 'Agfa',
                'slug' => 'agfa',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 5,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000063',
                'name' => 'Alcatel',
                'slug' => 'alcatel',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 6,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000080',
                'name' => 'Alps',
                'slug' => 'alps',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 7,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000098',
                'name' => 'Amstrad',
                'slug' => 'amstrad',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 8,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000101',
                'name' => 'Anadex',
                'slug' => 'anadex',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 9,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000120',
                'name' => 'Apple',
                'slug' => 'apple',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 10,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000204',
                'name' => 'Binder',
                'slug' => 'binder',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 11,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000218',
                'name' => 'Bosch',
                'slug' => 'bosch',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 12,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000228',
                'name' => 'British Telecom',
                'slug' => 'british-telecom',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 13,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000229',
                'name' => 'Brother',
                'slug' => 'brother',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 14,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000243',
                'name' => 'Bull',
                'slug' => 'bull',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 15,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000246',
                'name' => 'Burroughs',
                'slug' => 'burroughs',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 16,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000252',
                'name' => 'C.Itoh',
                'slug' => 'c-itoh',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 17,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000264',
                'name' => 'Canon',
                'slug' => 'canon',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 18,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000276',
                'name' => 'Casio',
                'slug' => 'casio',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 19,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000302',
                'name' => 'Citizen',
                'slug' => 'citizen',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 20,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000329',
                'name' => 'Commodore',
                'slug' => 'commodore',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 21,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000333',
                'name' => 'Compaq',
                'slug' => 'compaq',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 22,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000344',
                'name' => 'Compuprint',
                'slug' => 'compuprint',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 23,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001612',
                'name' => 'Copystar',
                'slug' => 'copystar',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 24,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000388',
                'name' => 'COT',
                'slug' => 'cot',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 25,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000391',
                'name' => 'CPF',
                'slug' => 'cpf',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 26,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001602',
                'name' => 'Danka',
                'slug' => 'danka',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 27,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '50101833',
                'name' => 'Dascom',
                'slug' => 'dascom',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 28,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000471',
                'name' => 'Dataproducts',
                'slug' => 'dataproducts',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 29,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000499',
                'name' => 'Dell',
                'slug' => 'dell',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 30,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000511',
                'name' => 'Detewe',
                'slug' => 'detewe',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 31,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000513',
                'name' => 'Develop',
                'slug' => 'develop',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 32,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000515',
                'name' => 'Diablo',
                'slug' => 'diablo',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 33,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000530',
                'name' => 'Digital Equipment Corp',
                'slug' => 'digital-equipment-corp',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 34,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20002488',
                'name' => 'Dymo',
                'slug' => 'dymo',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 35,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000569',
                'name' => 'EGT',
                'slug' => 'egt',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 36,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000586',
                'name' => 'Encad',
                'slug' => 'encad',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 37,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000593',
                'name' => 'Epson',
                'slug' => 'epson',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 38,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000623',
                'name' => 'Facit',
                'slug' => 'facit',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 39,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000652',
                'name' => 'Fujitsu',
                'slug' => 'fujitsu',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 40,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000653',
                'name' => 'Fujitsu General',
                'slug' => 'fujitsu-general',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 41,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000662',
                'name' => 'GCC',
                'slug' => 'gcc',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 42,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000681',
                'name' => 'Gestetner',
                'slug' => 'gestetner',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 43,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000730',
                'name' => 'Hitachi',
                'slug' => 'hitachi',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 44,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000728',
                'name' => 'HP',
                'slug' => 'hp',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 45,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000746',
                'name' => 'IBM',
                'slug' => 'ibm',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 46,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000750',
                'name' => 'ICL',
                'slug' => 'icl',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 47,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001768',
                'name' => 'Imagistics',
                'slug' => 'imagistics',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 48,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20002568',
                'name' => 'Infoprint Solutions Company',
                'slug' => 'infoprint-solutions-company',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 49,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000784',
                'name' => 'Infotec',
                'slug' => 'infotec',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 50,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000827',
                'name' => 'Jetfax',
                'slug' => 'jetfax',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 51,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000841',
                'name' => 'Kentek',
                'slug' => 'kentek',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 52,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000849',
                'name' => 'KMP',
                'slug' => 'kmp',
                'website' => '',
                'description' => 'COM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 53,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000851',
                'name' => 'Kodak',
                'slug' => 'kodak',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 54,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001164',
                'name' => 'Konica Minolta',
                'slug' => 'konica-minolta',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 55,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000984',
                'name' => 'Kyocera',
                'slug' => 'kyocera',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 56,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000861',
                'name' => 'Lanier',
                'slug' => 'lanier',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 57,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000868',
                'name' => 'Lasermaster',
                'slug' => 'lasermaster',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 58,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000886',
                'name' => 'Lexmark',
                'slug' => 'lexmark',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 59,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000946',
                'name' => 'Memorex',
                'slug' => 'memorex',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 60,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000969',
                'name' => 'Microplex',
                'slug' => 'microplex',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 61,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000989',
                'name' => 'Mitsubishi',
                'slug' => 'mitsubishi',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 62,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000999',
                'name' => 'Monroe',
                'slug' => 'monroe',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 63,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001003',
                'name' => 'Motorola',
                'slug' => 'motorola',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 64,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001013',
                'name' => 'Muratec',
                'slug' => 'muratec',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 65,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000068',
                'name' => 'Nakajima',
                'slug' => 'nakajima',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 66,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001026',
                'name' => 'NCR',
                'slug' => 'ncr',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 67,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001029',
                'name' => 'NEC',
                'slug' => 'nec',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 68,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001047',
                'name' => 'Nokia',
                'slug' => 'nokia',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 69,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20002389',
                'name' => 'NRG',
                'slug' => 'nrg',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 70,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001067',
                'name' => 'OCE',
                'slug' => 'oce',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 71,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001074',
                'name' => 'OKI',
                'slug' => 'oki',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 72,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001076',
                'name' => 'Olivetti',
                'slug' => 'olivetti',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 73,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001077',
                'name' => 'Olympia',
                'slug' => 'olympia',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 74,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001079',
                'name' => 'Omnifax',
                'slug' => 'omnifax',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 75,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001080',
                'name' => 'Omron',
                'slug' => 'omron',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 76,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001086',
                'name' => 'OTC',
                'slug' => 'otc',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 77,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001099',
                'name' => 'Panasonic',
                'slug' => 'panasonic',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 78,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '50096914',
                'name' => 'Pantum',
                'slug' => 'pantum',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 79,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001109',
                'name' => 'Pelikan',
                'slug' => 'pelikan',
                'website' => '',
                'description' => 'COM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 80,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001122',
                'name' => 'Philips',
                'slug' => 'philips',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 81,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001128',
                'name' => 'Pitney Bowes',
                'slug' => 'pitney-bowes',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 82,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001607',
                'name' => 'Primera',
                'slug' => 'primera',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 83,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001150',
                'name' => 'Printronix',
                'slug' => 'printronix',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 84,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001154',
                'name' => 'Privileg',
                'slug' => 'privileg',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 85,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001161',
                'name' => 'PSI',
                'slug' => 'psi',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 86,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001648',
                'name' => 'Quadient',
                'slug' => 'quadient',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 87,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001196',
                'name' => 'Regma',
                'slug' => 'regma',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 88,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001207',
                'name' => 'Rena',
                'slug' => 'rena',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 89,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001210',
                'name' => 'Rex Rotary',
                'slug' => 'rex-rotary',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 90,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001214',
                'name' => 'Ricoh',
                'slug' => 'ricoh',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 91,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001988',
                'name' => 'Riso',
                'slug' => 'riso',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 92,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001218',
                'name' => 'Roland',
                'slug' => 'roland',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 93,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001237',
                'name' => 'Sagem',
                'slug' => 'sagem',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 94,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001240',
                'name' => 'Samsung',
                'slug' => 'samsung',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 95,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001250',
                'name' => 'Sanyo',
                'slug' => 'sanyo',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 96,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001257',
                'name' => 'Savin',
                'slug' => 'savin',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 97,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001279',
                'name' => 'Seiko Precision',
                'slug' => 'seiko-precision',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 98,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001280',
                'name' => 'Seikosha',
                'slug' => 'seikosha',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 99,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001284',
                'name' => 'Selex',
                'slug' => 'selex',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 100,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001289',
                'name' => 'Sharp',
                'slug' => 'sharp',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 101,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001299',
                'name' => 'Silver Reed',
                'slug' => 'silver-reed',
                'website' => '',
                'description' => 'COM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 102,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20002769',
                'name' => 'Sindoh',
                'slug' => 'sindoh',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 103,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001305',
                'name' => 'Smith Corona',
                'slug' => 'smith-corona',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 104,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001311',
                'name' => 'Sony',
                'slug' => 'sony',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 105,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001328',
                'name' => 'Star Micronics',
                'slug' => 'star-micronics',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 106,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001348',
                'name' => 'Swintec',
                'slug' => 'swintec',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 107,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20000920',
                'name' => 'Tally Genicom',
                'slug' => 'tally-genicom',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 108,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001383',
                'name' => 'TEC',
                'slug' => 'tec',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 109,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001400',
                'name' => 'Telekom',
                'slug' => 'telekom',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 110,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001405',
                'name' => 'Telesystems',
                'slug' => 'telesystems',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 111,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001605',
                'name' => 'Tenovis',
                'slug' => 'tenovis',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 112,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001421',
                'name' => 'Texas Instruments',
                'slug' => 'texas-instruments',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 113,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001434',
                'name' => 'Toshiba',
                'slug' => 'toshiba',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 114,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001453',
                'name' => 'Triumph-Adler',
                'slug' => 'triumph-adler',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 115,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001476',
                'name' => 'Unisys',
                'slug' => 'unisys',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 116,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001484',
                'name' => 'Utax',
                'slug' => 'utax',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 117,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001511',
                'name' => 'Wang',
                'slug' => 'wang',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 118,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001295',
                'name' => 'Wincor-Nixdorf',
                'slug' => 'wincor-nixdorf',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 119,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001145',
                'name' => 'Xante',
                'slug' => 'xante',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 120,
                'uuid_id' => Text::uuid(),
                'foreign_key' => '20001535',
                'name' => 'Xerox',
                'slug' => 'xerox',
                'website' => '',
                'description' => 'OEM',
                'logo' => '',
                'image' => '',
                'status' => 1,
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
        ];

        $table = $this->table('product_manufacturers');
        $table->insert($data)->save();
    }
}
