<?php
declare(strict_types=1);

/* 
 * MIT License
 *
 * Copyright (c) 2018-present, Marks Software GmbH (https://www.marks-software.de/)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
use Cake\I18n\DateTime;
use Cake\Utility\Text;
use Migrations\AbstractSeed;

/**
 * Class SettingsSeed
 */
class SettingsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     *
     * @return void
     */
    public function run(): void
    {
        $dateTime = DateTime::now();

        $data = [
            [
                'id' => 1,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'theme',
                'name' => 'backendTheme',
                'value' => 'BechlemConnectLight',
                'title' => 'Backend Theme',
                'description' => 'Detault backend theme',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 2,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'theme',
                'name' => 'frontendTheme',
                'value' => 'BechlemConnectLight',
                'title' => 'Frontend Theme',
                'description' => 'Detault frontend theme',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 3,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'theme',
                'name' => 'backendNavbarColor',
                'value' => 'dark',
                'title' => 'Backend navbar color',
                'description' => 'Detault backend navbar color. Following colors are available: white, warning, orange, dark, light',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 4,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'theme',
                'name' => 'backendNavbarTextColor',
                'value' => 'white',
                'title' => 'Backend navbar text color',
                'description' => 'Detault backend navbar text color. Following colors are available: white, primary, secondary, info, success, danger, indigo, purple, pink, navy, lightblue, teal, cyan, gray, gray-dark, dark, light',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 5,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'theme',
                'name' => 'backendNavbarBackgroundColor',
                'value' => 'maroon',
                'title' => 'Backend navbar background color',
                'description' => 'Detault backend navbar background color. Following colors are available: primary, secondary, warning, info, danger, success, indigo, lightblue, navy, purple, fuchsia, pink, maroon, orange, lime, teal, olive, cyan, gray, gray-dark, dark',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 6,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'theme',
                'name' => 'backendSidebarColor',
                'value' => 'dark',
                'title' => 'Backend sidebar color',
                'description' => 'Detault backend sidebar color. Following colors are available: light, dark',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 7,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'theme',
                'name' => 'backendSidebarTextColor',
                'value' => 'maroon',
                'title' => 'Backend sidebar text color',
                'description' => 'Detault backend sidebar text color. Following colors are available: primary, warning, info, danger, success, indigo, lightblue, navy, purple, fuchsia, pink, maroon, orange, lime, teal, olive',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 8,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'theme',
                'name' => 'backendSidebarBackgroundColor',
                'value' => 'maroon',
                'title' => 'Backend sidebar background color',
                'description' => 'Detault backend sidebar background color. Following colors are available: primary, warning, info, danger, success, indigo, lightblue, navy, purple, fuchsia, pink, maroon, orange, lime, teal, olive',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 9,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'theme',
                'name' => 'backendLinkTextColor',
                'value' => 'maroon',
                'title' => 'Backend link text color',
                'description' => 'Detault backend link text color. Following colors are available: primary, warning, info, danger, success, indigo, lightblue, navy, purple, fuchsia, pink, maroon, orange, lime, teal, olive',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 10,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'theme',
                'name' => 'backendButtonColor',
                'value' => 'outline-dark',
                'title' => 'Backend button color',
                'description' => 'Detault backend button color. Following colors are available: dark, light, primary, secondary, info, success, warning, danger, outline-dark, outline-light, outline-primary, outline-secondary, outline-info, outline-success, outline-warning, outline-danger',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 11,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'theme',
                'name' => 'backendBoxColor',
                'value' => 'maroon',
                'title' => 'Backend box color',
                'description' => 'Detault backend box color. Following colors are available: primary, secondary, warning, info, danger, success, indigo, lightblue, navy, purple, fuchsia, pink, maroon, orange, lime, teal, olive, cyan, dark, gray-dark, gray',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 12,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'theme',
                'name' => 'backendControlSidebar',
                'value' => 1,
                'title' => 'Backend control sidebar',
                'description' => 'Display backend control sidebar.',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 13,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'theme',
                'name' => 'frontendNavbarColor',
                'value' => 'dark',
                'title' => 'Frontend navbar color',
                'description' => 'Detault frontend navbar color. Following colors are available: white, warning, orange, light, dark',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 14,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'theme',
                'name' => 'frontendNavbarTextColor',
                'value' => 'white',
                'title' => 'Frontend navbar text color',
                'description' => 'Detault frontend navbar text color. Following colors are available: white, primary, secondary, info, success, danger, indigo, purple, pink, navy, lightblue, teal, cyan, dark, gray-dark, gray, light, dark',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 15,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'theme',
                'name' => 'frontendNavbarBackgroundColor',
                'value' => 'navy',
                'title' => 'Frontend navbar background color',
                'description' => 'Detault frontend navbar background color. Following colors are available: primary, secondary, warning, info, danger, success, indigo, lightblue, navy, purple, fuchsia, pink, maroon, orange, lime, teal, olive, cyan, dark, gray-dark, gray',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 16,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'theme',
                'name' => 'frontendSidebarColor',
                'value' => 'dark',
                'title' => 'Frontend sidebar color',
                'description' => 'Detault frontend sidebar color. Following colors are available: light, dark',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 17,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'theme',
                'name' => 'frontendSidebarTextColor',
                'value' => 'white',
                'title' => 'Frontend sidebar text color',
                'description' => 'Detault frontend sidebar text color. Following colors are available: primary, warning, info, danger, success, indigo, lightblue, navy, purple, fuchsia, pink, maroon, orange, lime, teal, olive',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 18,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'theme',
                'name' => 'frontendSidebarBackgroundColor',
                'value' => 'navy',
                'title' => 'Frontend sidebar background color',
                'description' => 'Detault frontend sidebar background color. Following colors are available: primary, warning, info, danger, success, indigo, lightblue, navy, purple, fuchsia, pink, maroon, orange, lime, teal, olive',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 19,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'theme',
                'name' => 'frontendLinkTextColor',
                'value' => 'navy',
                'title' => 'Frontend link text color',
                'description' => 'Detault frontend link text color. Following colors are available: primary, warning, info, danger, success, indigo, lightblue, navy, purple, fuchsia, pink, maroon, orange, lime, teal, olive',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 20,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'theme',
                'name' => 'frontendButtonColor',
                'value' => 'outline-dark',
                'title' => 'Frontend button color',
                'description' => 'Detault frontend button color. Following colors are available: primary, secondary, success, info, danger, warning, light, dark, outline-primary, outline-secondary, outline-success, outline-info, outline-danger, outline-warning, outline-light, outline-dark, gradient-primary, gradient-secondary, gradient-success, gradient-info, gradient-danger, gradient-warning',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 21,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'theme',
                'name' => 'frontendBoxColor',
                'value' => 'secondary',
                'title' => 'Frontend Box Color',
                'description' => 'Detault frontend box color. Following colors are available: primary, secondary, warning, info, danger, success, indigo, lightblue, navy, purple, fuchsia, pink, maroon, orange, lime, teal, olive, cyan, dark, gray-dark, gray',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 22,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'theme',
                'name' => 'frontendControlSidebar',
                'value' => 1,
                'title' => 'Frontend control sidebar',
                'description' => 'Display frontend control sidebar.',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 23,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'site',
                'name' => 'siteTitlePrefix',
                'value' => '',
                'title' => 'Site title prefix',
                'description' => 'Default title prefix',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 24,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'site',
                'name' => 'siteTitle',
                'value' => 'Bechlem Connect Light',
                'title' => 'Site title',
                'description' => 'Default title',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 25,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'site',
                'name' => 'siteTitleSuffix',
                'value' => '',
                'title' => 'Site title suffix',
                'description' => 'Default title suffix',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 26,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'site',
                'name' => 'siteFaviconIcoUrl',
                'value' => '/bechlem_connect_light/img/favicons/favicon.ico',
                'title' => 'Site favicon ico url',
                'description' => 'Default favicon url',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 27,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'site',
                'name' => 'siteLogoImageUrl',
                'value' => '/bechlem_connect_light/img/logo.png',
                'title' => 'Site logo image url',
                'description' => 'Default logo image url',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 28,
                'domain_id' => 1,
                'uuid_id' => Text::uuid(),
                'foreign_key' => NULL,
                'parameter' => 'site',
                'name' => 'siteLogoImageAlt',
                'value' => 'Bechlem Connect Light',
                'title' => 'Site logo image alt',
                'description' => 'Default logo image alt',
                'created' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'created_by' => 1,
                'modified' => $dateTime->i18nFormat('yyyy-MM-dd HH:mm:ss'),
                'modified_by' => 1,
                'deleted' => NULL,
                'deleted_by' => NULL,
            ],
        ];

        $table = $this->table('settings');
        $table->insert($data)->save();
    }
}
